ArkScript: Ark::types Namespace Reference
Ark::types Namespace Reference
Namespaces
namespace details
Classes
struct Contract
A contract is a list of typed arguments that a function can follow.
class TypeCheckingError
struct Typedef
A type definition within a contract.
Functions
template<typename... Ts, typename = details::AllSame<ValueType, Ts...>>
bool check (const std::vector< Value > &args, Ts... types)
Helper to see if a builtin has been given a wanted set of types.
ARK_API void generateError (const std::string_view &funcname, const std::vector< Contract > &contracts, const std::vector< Value > &args, VM &vm, std::ostream &os=std::cout, bool colorize=true)
Generate an error message based on a given set of types contracts provided argument list.
std::string typeListToString (const std::vector< ValueType > &types)
void displayContract (const std::string_view &funcname, const Contract &contract, const std::vector< Value > &args, VM &vm, std::ostream &os, const bool colorize)
Function Documentation
check()
template<typename... Ts, typename = details::AllSame<ValueType, Ts...>> bool Ark::types::check (const std::vector< Value > & args, Ts... types) nodiscard
Helper to see if a builtin has been given a wanted set of types.
Template Parameters
Ts Variadic argument list composed of ValueTypes
Parameters
args arguments passed to the function
types accepted types
Returns
true if the contract is respected
false otherwise
Definition at line 59 of file TypeChecker.hpp.
References Ark::types::details::checkN().
Referenced by Ark::Repl::registerBuiltins().
displayContract()
void Ark::types::displayContract (const std::string_view & funcname, const Contract & contract, const std::vector< Value > & args, VM & vm, std::ostream & os, const bool colorize)
Definition at line 32 of file TypeChecker.cpp.
References Ark::Any, Ark::types::Contract::arguments, std::to_string(), typeListToString(), Ark::types::Typedef::types, and Ark::types::Typedef::variadic.
Referenced by generateError().
generateError()
void Ark::types::generateError (const std::string_view & funcname, const std::vector< Contract > & contracts, const std::vector< Value > & args, VM & vm, std::ostream & os = std::cout, bool colorize = true)
Generate an error message based on a given set of types contracts provided argument list.
Parameters
funcname ArkScript name of the function
contracts types contracts the function can follow
args provided argument list
vm reference to the VM used for pretty printing closures
os output stream, default to cout
colorize enable output colorizing
Definition at line 149 of file TypeChecker.cpp.
References displayContract(), Ark::Undefined, and Ark::Value::valueType().
Referenced by Ark::types::TypeCheckingError::details().
typeListToString()
std::string Ark::types::typeListToString (const std::vector< ValueType > & types)
Definition at line 14 of file TypeChecker.cpp.
References Ark::Any, and std::to_string().
Referenced by displayContract().