ArkScript: Ark::BytecodeReader Class Reference
Ark::BytecodeReader Class Reference final
This class is just a helper to.
#include <BytecodeReader.hpp>
Public Member Functions
BytecodeReader ()=default
Construct a new Bytecode Reader object.
void feed (const std::string &file)
Construct needed data before displaying information about a given file.
void feed (const bytecode_t &bytecode)
Construct needed data before displaying information about a given bytecode.
bool checkMagic () const
Version version () const
unsigned long long timestamp () const
Return the read timestamp from the bytecode file.
std::vector< unsigned char > sha256 () const
Symbols symbols () const
Values values (const Symbols &symbols) const
Filenames filenames (const Values &values) const
InstLocations instLocations (const Filenames &filenames) const
Code code (const InstLocations &instLocations) const
std::optional< internal::InstLoc > findSourceLocation (const std::vector< internal::InstLoc > &inst_locations, std::size_t ip, std::size_t pp) const
Find the location of an instruction.
void display (BytecodeSegment segment=BytecodeSegment::All, std::optional< uint16_t > sStart=std::nullopt, std::optional< uint16_t > sEnd=std::nullopt, std::optional< uint16_t > cPage=std::nullopt) const
Display the bytecode opcode in a human friendly way.
Private Member Functions
uint16_t readNumber (std::size_t &i) const
Read a number from the bytecode, under the instruction pointer i.
Private Attributes
bytecode_t m_bytecode
Friends
class Ark::State
Detailed Description
This class is just a helper to.
check if a bytecode is valid
display it in a human-readable way by using the opcode names
Definition at line 85 of file BytecodeReader.hpp.
Constructor & Destructor Documentation
BytecodeReader()
Ark::BytecodeReader::BytecodeReader () default
Construct a new Bytecode Reader object.
Member Function Documentation
checkMagic()
bool Ark::BytecodeReader::checkMagic () const nodiscard
Check for the presence of the magic header
Returns
true if the magic 'ark\0' was found
Definition at line 40 of file BytecodeReader.cpp.
References m_bytecode, and Ark::internal::bytecode::Magic.
Referenced by code(), display(), Ark::State::doFile(), Ark::State::feed(), filenames(), instLocations(), main(), sha256(), symbols(), timestamp(), values(), and version().
code()
Code Ark::BytecodeReader::code (const InstLocations & instLocations) const nodiscard
Parameters
instLocations
Returns
Code
Definition at line 247 of file BytecodeReader.cpp.
References checkMagic(), Ark::internal::CODE_SEGMENT_START, Ark::InstLocations::end, instLocations(), m_bytecode, Ark::Code::pages, readNumber(), and Ark::Code::start.
Referenced by Ark::State::configure(), and display().
display()
void Ark::BytecodeReader::display (BytecodeSegment segment = BytecodeSegment::All, std::optional< uint16_t > sStart = std::nullopt, std::optional< uint16_t > sEnd = std::nullopt, std::optional< uint16_t > cPage = std::nullopt) const
Display the bytecode opcode in a human friendly way.
Parameters
segment selected bytecode segment that will be displayed
sStart start of the segment slice to display (Ignored in code segment if no page is available)
sEnd end of the segment slice to display (Ignored in code segment if no page is available)
cPage selected page of the code segment (Used only for the code segment)
< eg: Stack index, jump address, number
< Builtin, number
< Constant, number
< Symbol, number
< Symbol index, symbol
< Symbol index, constant
< Symbol index, symbol index
Definition at line 297 of file BytecodeReader.cpp.
References Ark::All, Ark::internal::APPEND, Ark::internal::APPEND_IN_PLACE, Ark::internal::APPEND_IN_PLACE_SYM, Ark::internal::APPEND_IN_PLACE_SYM_INDEX, Ark::internal::AT_SYM_INDEX_CONST, Ark::internal::AT_SYM_INDEX_SYM_INDEX, Ark::internal::AT_SYM_SYM, Ark::internal::BUILTIN, Ark::internal::Builtins::builtins, Ark::internal::CALL, Ark::internal::CALL_BUILTIN, Ark::internal::CALL_BUILTIN_WITHOUT_RETURN_ADDRESS, Ark::internal::CALL_CURRENT_PAGE, Ark::internal::CALL_SYMBOL, Ark::internal::CAPTURE, Ark::internal::CHECK_TYPE_OF, Ark::internal::CHECK_TYPE_OF_BY_INDEX, checkMagic(), Ark::Code, code(), Ark::internal::CONCAT, Ark::internal::CONCAT_IN_PLACE, Ark::internal::DECREMENT, Ark::internal::DECREMENT_BY_INDEX, Ark::internal::DECREMENT_STORE, Ark::internal::DEL, Ark::internal::EQ_CONST_JUMP_IF_TRUE, Ark::internal::EQ_SYM_INDEX_JUMP_IF_TRUE, filenames(), findSourceLocation(), Ark::internal::FUSED_MATH, Ark::internal::GET_CURRENT_PAGE_ADDR, Ark::internal::GET_FIELD, Ark::internal::GET_FIELD_FROM_SYMBOL, Ark::internal::GET_FIELD_FROM_SYMBOL_INDEX, Ark::internal::GT_CONST_JUMP_IF_FALSE, Ark::internal::GT_CONST_JUMP_IF_TRUE, Ark::internal::GT_SYM_JUMP_IF_FALSE, Ark::HeadersOnly, Ark::internal::INCREMENT, Ark::internal::INCREMENT_BY_INDEX, Ark::internal::INCREMENT_STORE, instLocations(), Ark::InstructionLocation, Ark::internal::InstructionNames, Ark::internal::JUMP, Ark::internal::LIST, Ark::internal::LOAD_CONST, Ark::internal::LOAD_CONST_LOAD_CONST, Ark::internal::LOAD_CONST_SET_VAL, Ark::internal::LOAD_CONST_STORE, Ark::internal::LOAD_SYMBOL, Ark::internal::LOAD_SYMBOL_BY_INDEX, Ark::internal::LT_CONST_JUMP_IF_FALSE, Ark::internal::LT_CONST_JUMP_IF_TRUE, Ark::internal::LT_LEN_SYM_JUMP_IF_FALSE, Ark::internal::LT_SYM_JUMP_IF_FALSE, Ark::internal::MAKE_CLOSURE, Ark::internal::MUL_BY, Ark::internal::MUL_BY_INDEX, Ark::internal::MUL_SET_VAL, Ark::internal::NEQ_CONST_JUMP_IF_TRUE, Ark::internal::NEQ_SYM_JUMP_IF_FALSE, Ark::Number, Ark::PageAddr, Ark::internal::PLUGIN, Ark::internal::POP_JUMP_IF_FALSE, Ark::internal::POP_JUMP_IF_TRUE, Ark::internal::Raw, Ark::internal::RENAME_NEXT_CAPTURE, Ark::internal::RESET_SCOPE_JUMP, Ark::internal::SET_VAL, Ark::internal::SET_VAL_FROM, Ark::internal::SET_VAL_FROM_INDEX, Ark::internal::SET_VAL_HEAD, Ark::internal::SET_VAL_HEAD_BY_INDEX, Ark::internal::SET_VAL_TAIL, Ark::internal::SET_VAL_TAIL_BY_INDEX, sha256(), Ark::internal::STORE, Ark::internal::STORE_FROM, Ark::internal::STORE_FROM_INDEX, Ark::internal::STORE_HEAD, Ark::internal::STORE_HEAD_BY_INDEX, Ark::internal::STORE_LEN, Ark::internal::STORE_LIST, Ark::internal::STORE_REF, Ark::internal::STORE_TAIL, Ark::internal::STORE_TAIL_BY_INDEX, Ark::String, Ark::internal::Symbol, Ark::Symbols, symbols(), timestamp(), std::to_string(), Ark::Values, values(), and version().
Referenced by main().
feed() [1/2]
void Ark::BytecodeReader::feed (const bytecode_t & bytecode)
Construct needed data before displaying information about a given bytecode.
Parameters
bytecode
Definition at line 17 of file BytecodeReader.cpp.
References m_bytecode.
feed() [2/2]
void Ark::BytecodeReader::feed (const std::string & file)
Construct needed data before displaying information about a given file.
Parameters
file filename of the bytecode file
Definition at line 22 of file BytecodeReader.cpp.
References m_bytecode.
Referenced by Ark::State::doFile(), Ark::State::feed(), and main().
filenames()
Filenames Ark::BytecodeReader::filenames (const Values & values) const nodiscard
Parameters
values
Returns
Filenames
Definition at line 174 of file BytecodeReader.cpp.
References checkMagic(), Ark::Filenames::end, Ark::Values::end, Ark::Filenames::filenames, Ark::internal::FILENAMES_TABLE_START, m_bytecode, readNumber(), Ark::Filenames::start, and values().
Referenced by Ark::State::configure(), display(), and instLocations().
findSourceLocation()
std::optional< InstLoc > Ark::BytecodeReader::findSourceLocation (const std::vector< internal::InstLoc > & inst_locations, std::size_t ip, std::size_t pp) const
Find the location of an instruction.
Parameters
inst_locations
ip
pp
Returns
Definition at line 274 of file BytecodeReader.cpp.
Referenced by display().
instLocations()
InstLocations Ark::BytecodeReader::instLocations (const Filenames & filenames) const nodiscard
Parameters
filenames
Returns
InstLocations
Definition at line 204 of file BytecodeReader.cpp.
References checkMagic(), Ark::internal::deserializeBE(), Ark::Filenames::end, Ark::InstLocations::end, filenames(), Ark::internal::INST_LOC_TABLE_START, Ark::InstLocations::locations, m_bytecode, readNumber(), and Ark::InstLocations::start.
Referenced by code(), Ark::State::configure(), and display().
readNumber()
uint16_t Ark::BytecodeReader::readNumber (std::size_t & i) const nodiscard private
Read a number from the bytecode, under the instruction pointer i.
Parameters
i this parameter is being modified to point to the next value
Returns
uint16_t the number we read (big endian)
Definition at line 718 of file BytecodeReader.cpp.
References m_bytecode.
Referenced by code(), filenames(), instLocations(), symbols(), and values().
sha256()
std::vector< unsigned char > Ark::BytecodeReader::sha256 () const nodiscard
Returns
std::vector<unsigned char> bytecode sha
Definition at line 79 of file BytecodeReader.cpp.
References checkMagic(), Ark::internal::bytecode::HeaderSize, and m_bytecode.
Referenced by Ark::State::configure(), and display().
symbols()
Symbols Ark::BytecodeReader::symbols () const nodiscard
Returns
Symbols
Definition at line 90 of file BytecodeReader.cpp.
References checkMagic(), Ark::Symbols::end, Ark::internal::bytecode::HeaderSize, m_bytecode, readNumber(), Ark::Symbols::start, Ark::internal::SYM_TABLE_START, and Ark::Symbols::symbols.
Referenced by Ark::State::configure(), display(), and values().
timestamp()
unsigned long long Ark::BytecodeReader::timestamp () const nodiscard
Return the read timestamp from the bytecode file.
Returns
unsigned long long
Definition at line 61 of file BytecodeReader.cpp.
References checkMagic(), Ark::internal::bytecode::HeaderSize, and m_bytecode.
Referenced by display().
values()
Values Ark::BytecodeReader::values (const Symbols & symbols) const nodiscard
Parameters
symbols
Returns
Values
Definition at line 118 of file BytecodeReader.cpp.
References checkMagic(), Ark::internal::ieee754::deserialize(), Ark::internal::deserializeLE(), Ark::Symbols::end, Ark::Values::end, Ark::internal::FUNC_TYPE, m_bytecode, Ark::internal::NUMBER_TYPE, readNumber(), Ark::Values::start, Ark::internal::STRING_TYPE, symbols(), Ark::internal::VAL_TABLE_START, and Ark::Values::values.
Referenced by Ark::State::configure(), display(), and filenames().
version()
Version Ark::BytecodeReader::version () const nodiscard
Returns
Version compiler version used to create the given bytecode file
Definition at line 49 of file BytecodeReader.cpp.
References checkMagic(), m_bytecode, Ark::internal::bytecode::Magic, and Ark::internal::bytecode::Version.
Referenced by Ark::State::configure(), and display().
Friends And Related Symbol Documentation
Ark::State
friend class Ark::State friend
Definition at line 185 of file BytecodeReader.hpp.
Member Data Documentation
m_bytecode
bytecode_t Ark::BytecodeReader::m_bytecode private
Definition at line 188 of file BytecodeReader.hpp.
Referenced by checkMagic(), code(), feed(), feed(), filenames(), instLocations(), readNumber(), sha256(), symbols(), timestamp(), values(), and version().
The documentation for this class was generated from the following files:
/Users/fola/Documents/ArkScript/Ark/include/Ark/Compiler/BytecodeReader.hpp
/Users/fola/Documents/ArkScript/Ark/src/arkreactor/Compiler/BytecodeReader.cpp