ArkScript: JsonCompiler Class Reference
JsonCompiler Class Reference final
#include <JsonCompiler.hpp>
Public Member Functions
JsonCompiler (unsigned debug, const std::vector< std::filesystem::path > &lib_env, uint16_t features=0)
Construct a new JsonCompiler object.
void feed (const std::string &filename)
Feed the different variables with information taken from the given source code file.
std::string compile ()
Start the compilation.
Private Member Functions
std::string _compile (const Ark::internal::Node &node)
Compile a single node and return its representation.
std::string toJsonList (const Ark::internal::Node &node, std::size_t start)
Convert a NodeType::List to a JSON list.
Private Attributes
Ark::Welder m_welder
Detailed Description
Definition at line 11 of file JsonCompiler.hpp.
Constructor & Destructor Documentation
JsonCompiler()
JsonCompiler::JsonCompiler (unsigned debug, const std::vector< std::filesystem::path > & lib_env, uint16_t features = 0)
Construct a new JsonCompiler object.
Parameters
debug the debug level
lib_env list of path to the directories of the std lib
features compiler features to enable. By default, none are active to be able to dump a file AST without any processing
Definition at line 13 of file JsonCompiler.cpp.
Member Function Documentation
_compile()
std::string JsonCompiler::_compile (const Ark::internal::Node & node) private
Compile a single node and return its representation.
Parameters
node
Returns
const std::string&
Definition at line 27 of file JsonCompiler.cpp.
References _compile(), Ark::internal::FilePos::column, Ark::internal::Node::constList(), Ark::internal::Node::filename(), Ark::internal::Node::keyword(), Ark::internal::FilePos::line, Ark::internal::Node::nodeType(), Ark::internal::nodeTypes, Ark::internal::Node::number(), Ark::internal::Node::position(), Ark::internal::FileSpan::start, Ark::internal::Node::string(), and toJsonList().
Referenced by _compile(), compile(), and toJsonList().
compile()
std::string JsonCompiler::compile ()
Start the compilation.
Returns
Definition at line 22 of file JsonCompiler.cpp.
References _compile(), Ark::Welder::ast(), and m_welder.
Referenced by main().
feed()
void JsonCompiler::feed (const std::string & filename)
Feed the different variables with information taken from the given source code file.
Parameters
filename the name of the file
Definition at line 17 of file JsonCompiler.cpp.
References Ark::Welder::computeASTFromFile(), and m_welder.
Referenced by main().
toJsonList()
std::string JsonCompiler::toJsonList (const Ark::internal::Node & node, std::size_t start) private
Convert a NodeType::List to a JSON list.
Parameters
node
start
Returns
std::string
Definition at line 278 of file JsonCompiler.cpp.
References _compile(), and Ark::internal::Node::constList().
Referenced by _compile().
Member Data Documentation
m_welder
Ark::Welder JsonCompiler::m_welder private
Definition at line 38 of file JsonCompiler.hpp.
Referenced by compile(), and feed().
The documentation for this class was generated from the following files:
/Users/fola/Documents/ArkScript/Ark/include/CLI/JsonCompiler.hpp
/Users/fola/Documents/ArkScript/Ark/src/arkscript/JsonCompiler.cpp