ArkScript: /Users/fola/Documents/ArkScript/Ark/src/arkscript/main.cpp File Reference
main.cpp File Reference
#include <iostream>
#include <optional>
#include <filesystem>
#include <limits>
#include <cstdlib>
#include <clipp.h>
#include <fmt/core.h>
#include <fmt/color.h>
#include <Ark/Files.hpp>
#include <Ark/Compiler/BytecodeReader.hpp>
#include <CLI/JsonCompiler.hpp>
#include <CLI/REPL/Repl.hpp>
#include <CLI/Formatter.hpp>
Macros
#define ARK_ERROR_EXIT_CODE (-1)
Functions
int main (int argc, char **argv)
Macro Definition Documentation
ARK_ERROR_EXIT_CODE
#define ARK_ERROR_EXIT_CODE (-1)
Definition at line 20 of file main.cpp.
Referenced by main().
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 23 of file main.cpp.
References Ark::All, ARK_COMPILER, ARK_ERROR_EXIT_CODE, ARK_FULL_VERSION, Ark::Welder::bytecode(), Ark::BytecodeReader::checkMagic(), Ark::Code, Formatter::codeModified(), JsonCompiler::compile(), Ark::Welder::computeASTFromFile(), Ark::DefaultFeatures, Ark::BytecodeReader::display(), Ark::State::doFile(), Ark::State::doString(), Ark::FeatureASTOptimizer, Ark::FeatureDumpIR, Ark::FeatureImportSolver, Ark::FeatureIROptimizer, Ark::FeatureMacroProcessor, Ark::BytecodeReader::feed(), JsonCompiler::feed(), Ark::Welder::generateBytecode(), Ark::HeadersOnly, Formatter::output(), Ark::Repl::run(), Ark::VM::run(), Formatter::run(), Ark::State::setArgs(), Ark::State::setDebug(), Ark::Symbols, and Ark::Values.