ArkScript: Ark::internal::Parser Class Reference
Ark::internal::Parser Class Reference final
#include <Parser.hpp>
Public Member Functions
Parser (unsigned debug, ParserMode mode=ParserMode::Interpret)
Constructs a new Parser object.
void process (const std::string &filename, const std::string &code)
Parse the given code.
const Node & ast () const noexcept
const std::vector< Import > & imports () const
Public Member Functions inherited from Ark::internal::BaseParser
BaseParser ()=default
Private Member Functions
Node positioned (Node node, FilePosition cursor) const
std::optional< Node > & positioned (std::optional< Node > &node, FilePosition cursor) const
std::optional< Node > node ()
std::optional< Node > letMutSet (FilePosition filepos)
std::optional< Node > del (FilePosition filepos)
std::optional< Node > condition (FilePosition filepos)
std::optional< Node > loop (FilePosition filepos)
std::optional< Node > import_ (FilePosition filepos)
std::optional< Node > block (FilePosition filepos)
std::optional< Node > functionArgs (FilePosition filepos)
std::optional< Node > function (FilePosition filepos)
std::optional< Node > macroCondition (FilePosition filepos)
std::optional< Node > macroArgs (FilePosition filepos)
std::optional< Node > macro (FilePosition filepos)
std::optional< Node > functionCall (FilePosition filepos)
std::optional< Node > list (FilePosition filepos)
std::optional< Node > number (FilePosition filepos)
std::optional< Node > string (FilePosition filepos)
std::optional< Node > field (FilePosition filepos)
std::optional< Node > symbol (FilePosition filepos)
std::optional< Node > spread (FilePosition filepos)
std::optional< Node > nil (FilePosition filepos)
std::optional< Node > atom ()
Try to parse an atom (number, string, spread, field, symbol, nil)
std::optional< Node > anyAtomOf (std::initializer_list< NodeType > types)
Try to parse an atom, if any, match its type against the given list.
std::optional< Node > nodeOrValue ()
Try to parse an atom first, if it fails try to parse a node.
std::optional< Node > wrapped (std::optional< Node >(Parser::*parser)(FilePosition), const std::string &name)
Try to parse using a given parser, prefixing and suffixing it with (...), handling comments around the parsed node.
Private Attributes
ParserMode m_mode
Logger m_logger
Node m_ast
std::vector< Import > m_imports
unsigned m_allow_macro_behavior
Toggled on when inside a macro definition, off afterward.
std::size_t m_nested_nodes
Nested node counter.
std::vector< std::function< std::optional< Node >(FilePosition)> > m_parsers
Additional Inherited Members
Protected Member Functions inherited from Ark::internal::BaseParser
void initParser (const std::string &filename, const std::string &code)
FilePosition getCursor () const
CodeErrorContext generateErrorContextAtCurrentPosition () const
void error (const std::string &error, FilePosition start_at, const std::optional< CodeErrorContext > &additional_context=std::nullopt) const
Create an error context and throw an error containing said context.
void errorWithNextToken (const std::string &message, const std::optional< CodeErrorContext > &additional_context=std::nullopt)
Fetch the next token (space and paren delimited) to generate an error.
void expectSuffixOrError (char suffix, const std::string &context, const std::optional< CodeErrorContext > &additional_context=std::nullopt)
Check for a closing char or generate an error.
long getCount ()
std::size_t getSize () const
bool isEOF () const
void backtrack (long n)
Backtrack to a given position (this is NOT an offset!)
bool accept (const CharPred &t, std::string *s=nullptr)
check if a Character Predicate was able to parse, call next() if matching
bool expect (const CharPred &t, std::string *s=nullptr)
heck if a Character Predicate was able to parse, call next() if matching ; throw a CodeError if it doesn't match
std::string peek () const
bool space (std::string *s=nullptr)
bool inlineSpace (std::string *s=nullptr)
bool comment (std::string *s=nullptr)
std::string spaceComment ()
std::string newlineOrComment ()
bool prefix (char c)
bool number (std::string *s=nullptr)
bool signedNumber (std::string *s=nullptr)
bool hexNumber (unsigned length, std::string *s=nullptr)
bool name (std::string *s=nullptr)
bool sequence (const std::string &s)
bool packageName (std::string *s=nullptr)
bool anyUntil (const CharPred &delim, std::string *s=nullptr)
Match any char that do not match the predicate.
bool oneOf (std::initializer_list< std::string > words, std::string *s=nullptr)
Fetch a token and try to match one of the given words.
Protected Attributes inherited from Ark::internal::BaseParser
std::string m_filename
Detailed Description
Definition at line 36 of file Parser.hpp.
Constructor & Destructor Documentation
Parser()
Ark::internal::Parser::Parser (unsigned debug, ParserMode mode = ParserMode::Interpret) explicit
Constructs a new Parser object.
Parameters
debug debug level
mode how the parser should behave regarding certain nodes and errors
Definition at line 7 of file Parser.cpp.
Member Function Documentation
anyAtomOf()
std::optional< Node > Ark::internal::Parser::anyAtomOf (std::initializer_list< NodeType > types) private
Try to parse an atom, if any, match its type against the given list.
Parameters
types authorized types
Returns
std::optional<Node> std::nullopt if the parsed atom didn't match the given types
Definition at line 1026 of file Parser.cpp.
References atom().
Referenced by functionCall().
ast()
const Node & Ark::internal::Parser::ast () const nodiscard noexcept
Returns
const Node& resulting AST after processing the given code
Definition at line 92 of file Parser.cpp.
References m_ast.
Referenced by Ark::Welder::computeAST(), Ark::internal::ImportSolver::parseImport(), Formatter::run(), and Formatter::runWithString().
atom()
std::optional< Node > Ark::internal::Parser::atom () private
Try to parse an atom (number, string, spread, field, symbol, nil)
Returns
std::optional<Node> std::nullopt if no atom could be parsed
Definition at line 994 of file Parser.cpp.
References Ark::internal::BaseParser::backtrack(), field(), Ark::internal::BaseParser::getCount(), Ark::internal::BaseParser::getCursor(), m_allow_macro_behavior, nil(), number(), spread(), string(), and symbol().
Referenced by anyAtomOf(), and nodeOrValue().
block()
std::optional< Node > Ark::internal::Parser::block (FilePosition filepos) private
Definition at line 418 of file Parser.cpp.
References Ark::internal::BaseParser::accept(), Ark::internal::Begin, Ark::internal::BaseParser::comment(), Ark::internal::BaseParser::expectSuffixOrError(), Ark::internal::BaseParser::generateErrorContextAtCurrentPosition(), Ark::internal::BaseParser::isEOF(), Ark::internal::List, Ark::internal::BaseParser::newlineOrComment(), nodeOrValue(), Ark::internal::BaseParser::oneOf(), and positioned().
condition()
std::optional< Node > Ark::internal::Parser::condition (FilePosition filepos) private
Definition at line 230 of file Parser.cpp.
References Ark::internal::BaseParser::comment(), Ark::internal::BaseParser::errorWithNextToken(), Ark::internal::If, Ark::internal::List, Ark::internal::BaseParser::newlineOrComment(), nodeOrValue(), Ark::internal::BaseParser::oneOf(), and positioned().
del()
std::optional< Node > Ark::internal::Parser::del (FilePosition filepos) private
Definition at line 210 of file Parser.cpp.
References Ark::internal::BaseParser::comment(), Ark::internal::Del, Ark::internal::BaseParser::errorWithNextToken(), Ark::internal::List, Ark::internal::BaseParser::name(), Ark::internal::BaseParser::newlineOrComment(), Ark::internal::BaseParser::oneOf(), positioned(), and Ark::internal::Symbol.
field()
std::optional< Node > Ark::internal::Parser::field (FilePosition filepos) private
Definition at line 933 of file Parser.cpp.
References Ark::internal::BaseParser::accept(), Ark::internal::BaseParser::errorWithNextToken(), Ark::internal::Field, Ark::internal::BaseParser::getCursor(), Ark::internal::BaseParser::name(), positioned(), and Ark::internal::Symbol.
Referenced by atom().
function()
std::optional< Node > Ark::internal::Parser::function (FilePosition filepos) private
Definition at line 531 of file Parser.cpp.
References Ark::internal::BaseParser::backtrack(), Ark::internal::BaseParser::comment(), Ark::internal::BaseParser::errorWithNextToken(), Ark::internal::Fun, functionArgs(), Ark::internal::BaseParser::getCount(), Ark::internal::BaseParser::getCursor(), Ark::internal::List, m_allow_macro_behavior, Ark::internal::BaseParser::newlineOrComment(), nodeOrValue(), Ark::internal::Node::nodeType(), Ark::internal::BaseParser::oneOf(), positioned(), Ark::internal::Node::push_back(), Ark::internal::Node::string(), and Ark::internal::Symbol.
functionArgs()
std::optional< Node > Ark::internal::Parser::functionArgs (FilePosition filepos) private
Definition at line 458 of file Parser.cpp.
References Ark::internal::BaseParser::accept(), Ark::internal::Node::attachCommentAfter(), Ark::internal::Capture, Ark::internal::BaseParser::comment(), Ark::internal::BaseParser::error(), Ark::internal::BaseParser::expect(), Ark::internal::BaseParser::getCursor(), Ark::internal::BaseParser::isEOF(), Ark::internal::List, Ark::internal::MutArg, Ark::internal::BaseParser::name(), Ark::internal::BaseParser::newlineOrComment(), Ark::internal::BaseParser::oneOf(), positioned(), Ark::internal::RefArg, Ark::internal::Node::setString(), Ark::internal::Symbol, and Ark::internal::Unused.
Referenced by function().
functionCall()
std::optional< Node > Ark::internal::Parser::functionCall (FilePosition filepos) private
Definition at line 753 of file Parser.cpp.
References Ark::internal::BaseParser::accept(), anyAtomOf(), Ark::internal::BaseParser::comment(), Ark::internal::BaseParser::error(), Ark::internal::BaseParser::expectSuffixOrError(), Ark::internal::Field, Ark::internal::BaseParser::generateErrorContextAtCurrentPosition(), Ark::internal::BaseParser::getCursor(), Ark::internal::BaseParser::isEOF(), Ark::internal::List, Ark::internal::BaseParser::newlineOrComment(), node(), nodeOrValue(), positioned(), and Ark::internal::Symbol.
import_()
std::optional< Node > Ark::internal::Parser::import_ (FilePosition filepos) private
Definition at line 288 of file Parser.cpp.
References Ark::internal::BaseParser::accept(), Ark::internal::Node::attachNearestCommentBefore(), Ark::internal::BaseParser::backtrack(), Ark::internal::FilePosition::col, Ark::internal::Import::col, Ark::internal::BaseParser::comment(), Ark::internal::BaseParser::error(), Ark::internal::BaseParser::errorWithNextToken(), Ark::internal::BaseParser::expectSuffixOrError(), Ark::internal::BaseParser::generateErrorContextAtCurrentPosition(), Ark::internal::BaseParser::getCount(), Ark::internal::BaseParser::getCursor(), Ark::internal::Import, Ark::internal::Import::is_glob, Ark::internal::BaseParser::isEOF(), Ark::internal::Import::line, Ark::internal::List, Ark::internal::Node::list(), m_imports, Ark::internal::BaseParser::name(), Ark::internal::BaseParser::newlineOrComment(), Ark::internal::BaseParser::oneOf(), Ark::internal::Import::package, Ark::internal::BaseParser::packageName(), positioned(), Ark::internal::Import::prefix, Ark::internal::Node::push_back(), Ark::internal::FilePosition::row, Ark::internal::BaseParser::space(), Ark::internal::Symbol, Ark::internal::Import::symbols, Ark::internal::Import::toPackageString(), and Ark::internal::Import::with_prefix.
imports()
const std::vector< Import > & Ark::internal::Parser::imports () const nodiscard
Returns
const std::vector<Import>& list of imports detected by the parser
Definition at line 97 of file Parser.cpp.
References m_imports.
Referenced by Ark::Welder::computeAST(), and Ark::internal::ImportSolver::parseImport().
letMutSet()
std::optional< Node > Ark::internal::Parser::letMutSet (FilePosition filepos) private
Definition at line 157 of file Parser.cpp.
References Ark::internal::BaseParser::backtrack(), Ark::internal::BaseParser::comment(), Ark::internal::BaseParser::error(), Ark::internal::BaseParser::errorWithNextToken(), Ark::internal::BaseParser::getCount(), Ark::internal::BaseParser::getCursor(), Ark::internal::Let, Ark::internal::List, m_allow_macro_behavior, Ark::internal::Macro, Ark::internal::Mut, Ark::internal::BaseParser::name(), Ark::internal::BaseParser::newlineOrComment(), nodeOrValue(), Ark::internal::Node::nodeType(), Ark::internal::nodeTypes, Ark::internal::BaseParser::oneOf(), positioned(), Ark::internal::Node::push_back(), Ark::internal::Set, Ark::internal::Spread, and Ark::internal::Symbol.
list()
std::optional< Node > Ark::internal::Parser::list (FilePosition filepos) private
Definition at line 797 of file Parser.cpp.
References Ark::internal::BaseParser::accept(), Ark::internal::BaseParser::comment(), Ark::internal::BaseParser::expectSuffixOrError(), Ark::internal::BaseParser::generateErrorContextAtCurrentPosition(), Ark::internal::BaseParser::isEOF(), Ark::internal::List, Ark::internal::BaseParser::newlineOrComment(), nodeOrValue(), positioned(), and Ark::internal::Symbol.
loop()
std::optional< Node > Ark::internal::Parser::loop (FilePosition filepos) private
Definition at line 264 of file Parser.cpp.
References Ark::internal::BaseParser::comment(), Ark::internal::BaseParser::errorWithNextToken(), Ark::internal::List, Ark::internal::BaseParser::newlineOrComment(), nodeOrValue(), Ark::internal::BaseParser::oneOf(), positioned(), and Ark::internal::While.
macro()
std::optional< Node > Ark::internal::Parser::macro (FilePosition filepos) private
Definition at line 685 of file Parser.cpp.
References Ark::internal::BaseParser::accept(), Ark::internal::BaseParser::backtrack(), Ark::internal::BaseParser::comment(), Ark::internal::BaseParser::errorWithNextToken(), Ark::internal::BaseParser::expectSuffixOrError(), Ark::internal::BaseParser::generateErrorContextAtCurrentPosition(), Ark::internal::BaseParser::getCount(), Ark::internal::BaseParser::getCursor(), m_allow_macro_behavior, Ark::internal::Macro, macroArgs(), Ark::internal::BaseParser::name(), Ark::internal::BaseParser::newlineOrComment(), nodeOrValue(), Ark::internal::BaseParser::oneOf(), positioned(), and Ark::internal::Symbol.
macroArgs()
std::optional< Node > Ark::internal::Parser::macroArgs (FilePosition filepos) private
Definition at line 628 of file Parser.cpp.
References Ark::internal::BaseParser::accept(), Ark::internal::BaseParser::backtrack(), Ark::internal::BaseParser::comment(), Ark::internal::BaseParser::errorWithNextToken(), Ark::internal::BaseParser::getCount(), Ark::internal::BaseParser::isEOF(), Ark::internal::List, Ark::internal::BaseParser::name(), Ark::internal::BaseParser::newlineOrComment(), positioned(), Ark::internal::BaseParser::sequence(), Ark::internal::Spread, and Ark::internal::Symbol.
Referenced by macro().
macroCondition()
std::optional< Node > Ark::internal::Parser::macroCondition (FilePosition filepos) private
Definition at line 595 of file Parser.cpp.
References Ark::internal::BaseParser::comment(), Ark::internal::BaseParser::errorWithNextToken(), Ark::internal::If, Ark::internal::Macro, Ark::internal::BaseParser::newlineOrComment(), nodeOrValue(), Ark::internal::BaseParser::oneOf(), and positioned().
nil()
std::optional< Node > Ark::internal::Parser::nil (FilePosition filepos) private
Definition at line 980 of file Parser.cpp.
References Ark::internal::BaseParser::accept(), Ark::internal::BaseParser::comment(), Ark::internal::Interpret, Ark::internal::List, m_mode, Ark::internal::BaseParser::newlineOrComment(), positioned(), and Ark::internal::Symbol.
Referenced by atom().
node()
std::optional< Node > Ark::internal::Parser::node () private
Definition at line 131 of file Parser.cpp.
References Ark::internal::BaseParser::backtrack(), Ark::internal::BaseParser::errorWithNextToken(), Ark::internal::BaseParser::getCount(), Ark::internal::BaseParser::getCursor(), m_nested_nodes, m_parsers, and Ark::MaxNestedNodes.
Referenced by functionCall(), nodeOrValue(), positioned(), positioned(), and process().
nodeOrValue()
std::optional< Node > Ark::internal::Parser::nodeOrValue () private
Try to parse an atom first, if it fails try to parse a node.
Returns
std::optional<Node> std::nullopt if no atom or node could be parsed
Definition at line 1039 of file Parser.cpp.
References atom(), and node().
Referenced by block(), condition(), function(), functionCall(), letMutSet(), list(), loop(), macro(), and macroCondition().
number()
std::optional< Node > Ark::internal::Parser::number (FilePosition filepos) private
Definition at line 826 of file Parser.cpp.
References Ark::internal::BaseParser::error(), Ark::Utils::isDouble(), positioned(), and Ark::internal::BaseParser::signedNumber().
Referenced by atom().
positioned() [1/2]
Node Ark::internal::Parser::positioned (Node node, FilePosition cursor) const nodiscard private
Definition at line 102 of file Parser.cpp.
References Ark::internal::BaseParser::getCursor(), Ark::internal::BaseParser::m_filename, and node().
Referenced by block(), condition(), del(), field(), function(), functionArgs(), functionCall(), import_(), letMutSet(), list(), loop(), macro(), macroArgs(), macroCondition(), nil(), number(), spread(), string(), and symbol().
positioned() [2/2]
std::optional< Node > & Ark::internal::Parser::positioned (std::optional< Node > & node, FilePosition cursor) const nodiscard private
Definition at line 115 of file Parser.cpp.
References Ark::internal::BaseParser::getCursor(), Ark::internal::BaseParser::m_filename, and node().
process()
void Ark::internal::Parser::process (const std::string & filename, const std::string & code)
Parse the given code.
Parameters
filename can be left empty, used for error generation
code content of the file
Definition at line 51 of file Parser.cpp.
References Ark::internal::BaseParser::backtrack(), Ark::internal::BaseParser::comment(), Ark::internal::BaseParser::errorWithNextToken(), Ark::internal::BaseParser::getCount(), Ark::internal::BaseParser::initParser(), Ark::internal::BaseParser::isEOF(), Ark::internal::Node::list(), m_ast, m_logger, Ark::internal::BaseParser::newlineOrComment(), node(), Ark::internal::BaseParser::peek(), Ark::internal::Node::push_back(), Ark::internal::BaseParser::spaceComment(), Ark::internal::Logger::traceEnd(), and Ark::internal::Logger::traceStart().
Referenced by Ark::Welder::computeAST(), Ark::internal::ImportSolver::parseImport(), Formatter::run(), and Formatter::runWithString().
spread()
std::optional< Node > Ark::internal::Parser::spread (FilePosition filepos) private
Definition at line 968 of file Parser.cpp.
References Ark::internal::BaseParser::errorWithNextToken(), Ark::internal::BaseParser::name(), positioned(), Ark::internal::BaseParser::sequence(), and Ark::internal::Spread.
Referenced by atom().
string()
std::optional< Node > Ark::internal::Parser::string (FilePosition filepos) private
Definition at line 840 of file Parser.cpp.
References Ark::internal::BaseParser::accept(), Ark::internal::BaseParser::backtrack(), utf8::decode(), Ark::internal::BaseParser::error(), Ark::internal::BaseParser::expectSuffixOrError(), Ark::internal::BaseParser::getCount(), Ark::internal::BaseParser::getCursor(), Ark::internal::BaseParser::hexNumber(), Ark::internal::Interpret, Ark::internal::BaseParser::isEOF(), m_mode, positioned(), and Ark::internal::String.
Referenced by atom().
symbol()
std::optional< Node > Ark::internal::Parser::symbol (FilePosition filepos) private
Definition at line 960 of file Parser.cpp.
References Ark::internal::BaseParser::name(), positioned(), and Ark::internal::Symbol.
Referenced by atom().
wrapped()
std::optional< Node > Ark::internal::Parser::wrapped (std::optional< Node >(Parser::* parser)(FilePosition), const std::string & name) private
Try to parse using a given parser, prefixing and suffixing it with (...), handling comments around the parsed node.
Parameters
parser parser method returning a std::optional<Node>
name construction name, eg "let", "condition"
Returns
std::optional<Node> std::nullopt if the parser didn't match
Definition at line 1049 of file Parser.cpp.
References Ark::internal::BaseParser::comment(), Ark::internal::BaseParser::expectSuffixOrError(), Ark::internal::BaseParser::generateErrorContextAtCurrentPosition(), Ark::internal::BaseParser::getCursor(), Ark::internal::BaseParser::name(), Ark::internal::BaseParser::newlineOrComment(), Ark::internal::BaseParser::prefix(), and Ark::internal::BaseParser::spaceComment().
Member Data Documentation
m_allow_macro_behavior
unsigned Ark::internal::Parser::m_allow_macro_behavior private
Toggled on when inside a macro definition, off afterward.
Definition at line 70 of file Parser.hpp.
Referenced by atom(), function(), letMutSet(), and macro().
m_ast
Node Ark::internal::Parser::m_ast private
Definition at line 68 of file Parser.hpp.
Referenced by ast(), and process().
m_imports
std::vector<Import> Ark::internal::Parser::m_imports private
Definition at line 69 of file Parser.hpp.
Referenced by import_(), and imports().
m_logger
Logger Ark::internal::Parser::m_logger private
Definition at line 67 of file Parser.hpp.
Referenced by process().
m_mode
ParserMode Ark::internal::Parser::m_mode private
Definition at line 66 of file Parser.hpp.
Referenced by nil(), and string().
m_nested_nodes
std::size_t Ark::internal::Parser::m_nested_nodes private
Nested node counter.
Definition at line 71 of file Parser.hpp.
Referenced by node().
m_parsers
std::vector<std::function<std::optional<Node>(FilePosition)> > Ark::internal::Parser::m_parsers private
Definition at line 72 of file Parser.hpp.
Referenced by node().
The documentation for this class was generated from the following files:
/Users/fola/Documents/ArkScript/Ark/include/Ark/Compiler/AST/Parser.hpp
/Users/fola/Documents/ArkScript/Ark/src/arkreactor/Compiler/AST/Parser.cpp