ArkScript: Ark::internal::ieee754 Namespace Reference
Ark::internal::ieee754 Namespace Reference
Classes
struct DecomposedDouble
Functions
template<class T >
constexpr T bswap (T i)
DecomposedDouble serialize (const double n)
double deserialize (const DecomposedDouble d)
Variables
static constexpr auto MaxLong = static_cast<double>(std::numeric_limits<std::int64_t>::max())
Function Documentation
bswap()
template<class T > T Ark::internal::ieee754::bswap (T i) constexpr
Definition at line 19 of file IEEE754Serializer.hpp.
Referenced by deserialize(), and serialize().
deserialize()
double Ark::internal::ieee754::deserialize (const DecomposedDouble d) inline nodiscard
Definition at line 54 of file IEEE754Serializer.hpp.
References bswap(), Ark::internal::ieee754::DecomposedDouble::exponent, Ark::internal::ieee754::DecomposedDouble::mantissa, and MaxLong.
Referenced by Ark::BytecodeReader::values().
serialize()
DecomposedDouble Ark::internal::ieee754::serialize (const double n) inline nodiscard
Definition at line 43 of file IEEE754Serializer.hpp.
References bswap(), and MaxLong.
Referenced by Ark::internal::IRCompiler::pushValueTable().
Variable Documentation
MaxLong
auto Ark::internal::ieee754::MaxLong = static_cast<double>(std::numeric_limits<std::int64_t>::max()) static constexpr
Definition at line 15 of file IEEE754Serializer.hpp.
Referenced by deserialize(), and serialize().