ArkScript: Ark::internal::Closure Class Reference
Ark::internal::Closure Class Reference
Closure management.
#include <Closure.hpp>
Public Member Functions
Closure (const ClosureScope &scope, PageAddr_t pa) noexcept
Construct a new Closure object.
Closure (const std::shared_ptr< ClosureScope > &scope_ptr, PageAddr_t pa) noexcept
Construct a new Closure object.
const ClosureScope & scope () const noexcept
ClosureScope & refScope () const noexcept
const std::shared_ptr< ClosureScope > & scopePtr () const
PageAddr_t pageAddr () const
bool hasFieldEndingWith (const std::string &end, const VM &vm) const
Used when generating error messages in the VM, to see if a symbol might have been wrongly fully qualified.
std::string toString (VM &vm) const noexcept
Print the closure to a string.
Private Attributes
std::shared_ptr< ClosureScope > m_scope
PageAddr_t m_page_addr
Friends
struct std::hash< Ark::internal::Closure >
ARK_API bool operator== (const Closure &A, const Closure &B)
ARK_API_INLINE bool operator< (const Closure &A, const Closure &B)
Detailed Description
Closure management.
Definition at line 34 of file Closure.hpp.
Constructor & Destructor Documentation
Closure() [1/2]
Ark::internal::Closure::Closure (const ClosureScope & scope, PageAddr_t pa) noexcept
Construct a new Closure object.
Parameters
scope the scope of the function turned into a closure
pa the current page address of the function turned into a closure
Definition at line 10 of file Closure.cpp.
Closure() [2/2]
Ark::internal::Closure::Closure (const std::shared_ptr< ClosureScope > & scope_ptr, PageAddr_t pa) noexcept
Construct a new Closure object.
Parameters
scope_ptr a shared pointer to the scope of the function turned into a closure
pa the current page address of the function turned into a closure
Definition at line 15 of file Closure.cpp.
Member Function Documentation
hasFieldEndingWith()
bool Ark::internal::Closure::hasFieldEndingWith (const std::string & end, const VM & vm) const nodiscard
Used when generating error messages in the VM, to see if a symbol might have been wrongly fully qualified.
Parameters
end
vm
Returns
true if the closure has a field which is the end of 'end'
Definition at line 20 of file Closure.cpp.
References m_scope.
Referenced by Ark::VM::getField().
pageAddr()
PageAddr_t Ark::internal::Closure::pageAddr () const inline nodiscard
Returns
PageAddr_t the bytecode page address this closure refers to
Definition at line 60 of file Closure.hpp.
References m_page_addr.
refScope()
ClosureScope & Ark::internal::Closure::refScope () const inline nodiscard noexcept
Definition at line 53 of file Closure.hpp.
References m_scope.
Referenced by Ark::VM::getField(), and Ark::VM::safeRun().
scope()
const ClosureScope & Ark::internal::Closure::scope () const inline nodiscard noexcept
Definition at line 52 of file Closure.hpp.
References m_scope.
scopePtr()
const std::shared_ptr< ClosureScope > & Ark::internal::Closure::scopePtr () const inline nodiscard
Definition at line 54 of file Closure.hpp.
References m_scope.
Referenced by Ark::VM::getField().
toString()
std::string Ark::internal::Closure::toString (VM & vm) const noexcept
Print the closure to a string.
Parameters
vm
Definition at line 27 of file Closure.cpp.
Referenced by Ark::VM::getField().
Friends And Related Symbol Documentation
operator<
ARK_API_INLINE bool operator< (const Closure & A, const Closure & B) friend
Definition at line 88 of file Closure.hpp.
operator==
ARK_API bool operator== (const Closure & A, const Closure & B) friend
Definition at line 41 of file Closure.cpp.
std::hash< Ark::internal::Closure >
friend struct std::hash< Ark::internal::Closure > friend
Definition at line 79 of file Closure.hpp.
Member Data Documentation
m_page_addr
PageAddr_t Ark::internal::Closure::m_page_addr private
Definition at line 85 of file Closure.hpp.
Referenced by pageAddr().
m_scope
std::shared_ptr<ClosureScope> Ark::internal::Closure::m_scope private
Definition at line 83 of file Closure.hpp.
Referenced by hasFieldEndingWith(), refScope(), scope(), and scopePtr().
The documentation for this class was generated from the following files:
/Users/fola/Documents/ArkScript/Ark/include/Ark/VM/Value/Closure.hpp
/Users/fola/Documents/ArkScript/Ark/src/arkreactor/VM/Value/Closure.cpp