ArkScript: Ark::helper Namespace Reference
Ark::helper Namespace Reference
Functions
Value tail (Value *a)
Value head (Value *a)
Value at (Value &container, Value &index, VM &vm)
Function Documentation
at()
Value Ark::helper::at (Value & container, Value & index, VM & vm) inline
Definition at line 73 of file VM.cpp.
References Ark::List, Ark::Value::list(), Ark::Number, Ark::Value::number(), Ark::String, Ark::Value::string(), Ark::VM::throwVMError(), Ark::Value::toString(), and Ark::Value::valueType().
Referenced by Ark::VM::safeRun().
head()
Value Ark::helper::head (Value * a) inline
Definition at line 51 of file VM.cpp.
References Ark::Value::constList(), Ark::List, Ark::internal::Builtins::nil, Ark::String, Ark::Value::string(), Ark::Value::stringRef(), and Ark::Value::valueType().
Referenced by Ark::VM::safeRun().
tail()
Value Ark::helper::tail (Value * a) inline
Definition at line 22 of file VM.cpp.
References Ark::Value::constList(), Ark::List, Ark::String, Ark::Value::string(), Ark::Value::stringRef(), and Ark::Value::valueType().
Referenced by Ark::VM::safeRun().