ArkScript: Ark::Value Class Reference
Ark::Value Class Reference
#include <Value.hpp>
Public Types
using Number_t = double
using String_t = std::string
using List_t = std::vector<Value>
using Ref_t = Value*
using Dict_t = internal::Dict
using Value_t
Public Member Functions
Value () noexcept
Construct a new Value object.
Value (ValueType type) noexcept
Construct a new Value object.
template<typename T >
Value (const ValueType type, T &&value) noexcept
Construct a new Value object.
Value (int value) noexcept
Value (double value) noexcept
Value (const String_t &value) noexcept
Value (const char *value) noexcept
Value (internal::PageAddr_t value) noexcept
Value (Procedure &&value) noexcept
Value (List_t &&value) noexcept
Value (internal::Closure &&value) noexcept
Value (UserType &&value) noexcept
Value (Dict_t &&value) noexcept
Value (Ref_t ref) noexcept
ValueType valueType () const noexcept
bool isFunction () const noexcept
bool isIndexable () const noexcept
Number_t number () const
const String_t & string () const
String_t & stringRef ()
const List_t & constList () const
List_t & list ()
const UserType & usertype () const
UserType & usertypeRef ()
const Dict_t & dict () const
Dict_t & dictRef ()
Ref_t reference () const
internal::PageAddr_t pageAddr () const
void push_back (const Value &value)
Add an element to the list held by the value (if the value type is set to list)
void push_back (Value &&value)
Add an element to the list held by the value (if the value type is set to list)
std::string toString (VM &vm, bool show_as_code=false) const noexcept
Private Member Functions
constexpr uint8_t typeNum () const noexcept
const Procedure & proc () const
const internal::Closure & closure () const
internal::Closure & refClosure ()
Private Attributes
ValueType m_type
Value_t m_value
Friends
class Ark::VM
class Ark::BytecodeReader
struct std::hash< Ark::Value >
ARK_API bool operator== (const Value &A, const Value &B)
ARK_API_INLINE bool operator< (const Value &A, const Value &B)
ARK_API_INLINE bool operator! (const Value &A)
Detailed Description
Definition at line 90 of file Value.hpp.
Member Typedef Documentation
Dict_t
using Ark::Value::Dict_t = internal::Dict
Definition at line 97 of file Value.hpp.
List_t
using Ark::Value::List_t = std::vector<Value>
Definition at line 95 of file Value.hpp.
Number_t
using Ark::Value::Number_t = double
Definition at line 93 of file Value.hpp.
Ref_t
using Ark::Value::Ref_t = Value*
Definition at line 96 of file Value.hpp.
String_t
using Ark::Value::String_t = std::string
Definition at line 94 of file Value.hpp.
Value_t
using Ark::Value::Value_t
Initial value:
 std::variant<
            Number_t,
            String_t,
            internal::PageAddr_t,
            Procedure,
            internal::Closure,
            UserType,
            List_t,
            std::shared_ptr<Dict_t>,
            Ref_t
            >
Definition at line 99 of file Value.hpp.
Constructor & Destructor Documentation
Value() [1/14]
Ark::Value::Value () noexcept
Construct a new Value object.
Definition at line 10 of file Value.cpp.
Value() [2/14]
Ark::Value::Value (ValueType type) explicit noexcept
Construct a new Value object.
Parameters
type the value type which is going to be held
Definition at line 14 of file Value.cpp.
References Ark::List, and Ark::String.
Value() [3/14]
template<typename T > Ark::Value::Value (const ValueType type, T && value) inline noexcept
Construct a new Value object.
Use at your own risks. Asking for a value type N and putting a non-matching value will result in errors at runtime.
Template Parameters
T
Parameters
type value type wanted
value value needed
Definition at line 135 of file Value.hpp.
Value() [4/14]
Ark::Value::Value (int value) explicit noexcept
Definition at line 23 of file Value.cpp.
Value() [5/14]
Ark::Value::Value (double value) explicit noexcept
Definition at line 27 of file Value.cpp.
Value() [6/14]
Ark::Value::Value (const String_t & value) explicit noexcept
Definition at line 31 of file Value.cpp.
Value() [7/14]
Ark::Value::Value (const char * value) explicit noexcept
Definition at line 35 of file Value.cpp.
Value() [8/14]
Ark::Value::Value (internal::PageAddr_t value) explicit noexcept
Definition at line 39 of file Value.cpp.
Value() [9/14]
Ark::Value::Value (Procedure && value) explicit noexcept
Definition at line 43 of file Value.cpp.
Value() [10/14]
Ark::Value::Value (List_t && value) explicit noexcept
Definition at line 47 of file Value.cpp.
Value() [11/14]
Ark::Value::Value (internal::Closure && value) explicit noexcept
Definition at line 51 of file Value.cpp.
Value() [12/14]
Ark::Value::Value (UserType && value) explicit noexcept
Definition at line 55 of file Value.cpp.
Value() [13/14]
Ark::Value::Value (Dict_t && value) explicit noexcept
Definition at line 59 of file Value.cpp.
Value() [14/14]
Ark::Value::Value (Ref_t ref) explicit noexcept
Definition at line 63 of file Value.cpp.
Member Function Documentation
closure()
const internal::Closure & Ark::Value::closure () const inline nodiscard private
Definition at line 212 of file Value.hpp.
constList()
const List_t & Ark::Value::constList () const inline nodiscard
Definition at line 168 of file Value.hpp.
Referenced by Ark::helper::head(), Ark::VM::safeRun(), and Ark::helper::tail().
dict()
const Dict_t & Ark::Value::dict () const inline nodiscard
Definition at line 174 of file Value.hpp.
dictRef()
Dict_t & Ark::Value::dictRef () inline nodiscard
Definition at line 175 of file Value.hpp.
isFunction()
bool Ark::Value::isFunction () const inline nodiscard noexcept
Definition at line 152 of file Value.hpp.
isIndexable()
bool Ark::Value::isIndexable () const inline nodiscard noexcept
Definition at line 157 of file Value.hpp.
Referenced by Ark::VM::safeRun().
list()
List_t & Ark::Value::list () inline nodiscard
Definition at line 169 of file Value.hpp.
Referenced by Ark::helper::at(), Ark::VM::createList(), push_back(), push_back(), Ark::VM::safeRun(), and Ark::State::setArgs().
number()
Number_t Ark::Value::number () const inline nodiscard
Definition at line 162 of file Value.hpp.
Referenced by Ark::helper::at(), and Ark::VM::safeRun().
pageAddr()
internal::PageAddr_t Ark::Value::pageAddr () const inline nodiscard
Definition at line 179 of file Value.hpp.
Referenced by Ark::VM::backtrace(), and Ark::VM::safeRun().
proc()
const Procedure & Ark::Value::proc () const inline nodiscard private
Definition at line 211 of file Value.hpp.
push_back() [1/2]
void Ark::Value::push_back (const Value & value)
Add an element to the list held by the value (if the value type is set to list)
Parameters
value
Definition at line 67 of file Value.cpp.
References list().
Referenced by Ark::VM::createList(), and Ark::VM::listAppendInPlace().
push_back() [2/2]
void Ark::Value::push_back (Value && value)
Add an element to the list held by the value (if the value type is set to list)
Parameters
value
Definition at line 72 of file Value.cpp.
References list().
refClosure()
internal::Closure & Ark::Value::refClosure () inline nodiscard private
Definition at line 213 of file Value.hpp.
Referenced by Ark::VM::getField(), and Ark::VM::safeRun().
reference()
Ref_t Ark::Value::reference () const inline nodiscard
Definition at line 177 of file Value.hpp.
Referenced by Ark::VM::safeRun().
string()
const String_t & Ark::Value::string () const inline nodiscard
Definition at line 164 of file Value.hpp.
Referenced by Ark::helper::at(), Ark::internal::ASTLowerer::compileExpression(), Ark::helper::head(), Ark::VM::safeRun(), and Ark::helper::tail().
stringRef()
String_t & Ark::Value::stringRef () inline nodiscard
Definition at line 165 of file Value.hpp.
Referenced by Ark::helper::head(), Ark::VM::safeRun(), and Ark::helper::tail().
toString()
std::string Ark::Value::toString (VM & vm, bool show_as_code = false) const noexcept
Definition at line 77 of file Value.cpp.
References Ark::Closure, Ark::CProc, Ark::Dict, Ark::False, Ark::InstPtr, Ark::List, Ark::Nil, Ark::Number, Ark::PageAddr, Ark::Reference, Ark::String, Ark::True, Ark::Undefined, and Ark::User.
Referenced by Ark::helper::at(), Ark::Repl::run(), and Ark::VM::safeRun().
typeNum()
uint8_t Ark::Value::typeNum () const inline nodiscard constexpr private noexcept
Definition at line 209 of file Value.hpp.
usertype()
const UserType & Ark::Value::usertype () const inline nodiscard
Definition at line 171 of file Value.hpp.
usertypeRef()
UserType & Ark::Value::usertypeRef () inline nodiscard
Definition at line 172 of file Value.hpp.
valueType()
ValueType Ark::Value::valueType () const inline nodiscard noexcept
Definition at line 151 of file Value.hpp.
Referenced by Ark::helper::at(), Ark::VM::backtrace(), Ark::types::generateError(), Ark::VM::getField(), Ark::helper::head(), Ark::VM::listAppendInPlace(), Ark::Repl::run(), Ark::VM::safeRun(), and Ark::helper::tail().
Friends And Related Symbol Documentation
Ark::BytecodeReader
friend class Ark::BytecodeReader friend
Definition at line 202 of file Value.hpp.
Ark::VM
friend class Ark::VM friend
Definition at line 201 of file Value.hpp.
operator!
ARK_API_INLINE bool operator! (const Value & A) friend
Definition at line 228 of file Value.hpp.
operator<
ARK_API_INLINE bool operator< (const Value & A, const Value & B) friend
Definition at line 216 of file Value.hpp.
operator==
ARK_API bool operator== (const Value & A, const Value & B) friend
Definition at line 144 of file Value.cpp.
std::hash< Ark::Value >
friend struct std::hash< Ark::Value > friend
Definition at line 202 of file Value.hpp.
Member Data Documentation
m_type
ValueType Ark::Value::m_type private
Definition at line 206 of file Value.hpp.
m_value
Value_t Ark::Value::m_value private
Definition at line 207 of file Value.hpp.
The documentation for this class was generated from the following files:
/Users/fola/Documents/ArkScript/Ark/include/Ark/VM/Value.hpp
/Users/fola/Documents/ArkScript/Ark/src/arkreactor/VM/Value.cpp