ArkScript: Ark::internal Namespace Reference
Ark::internal Namespace Reference
Namespaces
namespace Builtins
namespace bytecode
namespace ieee754
namespace IR
namespace Language
Classes
class ASTLowerer
The ArkScript AST to IR compiler.
class BaseParser
struct CharPred
class Closure
Closure management.
class ClosureScope
A class to store fields captured by a closure.
class ConditionalExecutor
Handles Conditional macros.
struct Declaration
class Dict
struct EntityWithOffset
struct ExecutionContext
struct FilePos
struct FilePosition
Describe a position in a given file ; handled by the BaseParser.
struct FileSpan
Describes a span for a node/atom in a file, its start position and end position.
class FunctionExecutor
Handles function macros.
class Future
struct Import
class ImportSolver
struct InstLoc
class IRCompiler
class IROptimizer
struct IsAlnum
struct IsAlpha
struct IsChar
struct IsDigit
struct IsEither
struct IsHex
struct IsInlineSpace
struct IsNot
struct IsSpace
struct IsSymbol
class LocalsLocator
class Logger
class MacroExecutor
A class that applies macros in a Node.
class MacroProcessor
The class handling the macros definitions and calls, given an AST.
class MacroScope
class NameResolutionPass
struct Namespace
class NamespaceScope
class Node
A node of an Abstract Syntax Tree for ArkScript.
class Optimizer
The ArkScript AST optimizer.
struct Package
class Parser
class Pass
An interface to describe compiler passes.
class ScopeResolver
class ScopeView
A class to handle the VM scope more efficiently.
class SharedLibrary
Handling a shared library as an ArkScript VM plugin.
class StaticScope
class SymbolExecutor
Handles Symbol macros.
struct type_uid
struct type_uid_impl
class utf8_char_t
struct ValTableElem
A Compiler Value class helper to handle multiple types.
struct Word
Typedefs
using PageAddr_t = uint16_t
Enumerations
enum class ParserMode { Interpret , Raw }
enum class NodeType {
Symbol , Capture , Keyword , String ,
Number , List , Spread , Field ,
Macro , Namespace , Unused
}
The different node types available.
enum class Keyword {
Fun , Let , Mut , Set ,
If , While , Begin , Import ,
Del
}
The different keywords available.
enum Instruction : uint8_t {
NOP = 0x00 , SYM_TABLE_START = 0xA1 , VAL_TABLE_START = 0xA2 , CODE_SEGMENT_START = 0xA3 ,
NUMBER_TYPE = 0xF1 , STRING_TYPE = 0xF2 , FUNC_TYPE = 0xF3 , FILENAMES_TABLE_START = 0xA4 ,
INST_LOC_TABLE_START = 0xA5 , LOAD_SYMBOL = 0x01 , LOAD_SYMBOL_BY_INDEX = 0x02 , LOAD_CONST = 0x03 ,
POP_JUMP_IF_TRUE = 0x04 , STORE = 0x05 , SET_VAL = 0x06 , POP_JUMP_IF_FALSE = 0x07 ,
JUMP = 0x08 , RET = 0x09 , HALT = 0x0a , PUSH_RETURN_ADDRESS = 0x0b ,
CALL = 0x0c , CAPTURE = 0x0d , RENAME_NEXT_CAPTURE = 0x0e , BUILTIN = 0x0f ,
DEL = 0x10 , MAKE_CLOSURE = 0x11 , GET_FIELD = 0x12 , PLUGIN = 0x13 ,
LIST = 0x14 , APPEND = 0x15 , CONCAT = 0x16 , APPEND_IN_PLACE = 0x17 ,
CONCAT_IN_PLACE = 0x18 , POP_LIST = 0x19 , POP_LIST_IN_PLACE = 0x1a , SET_AT_INDEX = 0x1b ,
SET_AT_2_INDEX = 0x1c , POP = 0x1d , SHORTCIRCUIT_AND = 0x1e , SHORTCIRCUIT_OR = 0x1f ,
CREATE_SCOPE = 0x20 , RESET_SCOPE_JUMP = 0x21 , POP_SCOPE = 0x22 , GET_CURRENT_PAGE_ADDR = 0x23 ,
FIRST_OPERATOR = 0x24 , ADD = 0x24 , SUB = 0x25 , MUL = 0x26 ,
DIV = 0x27 , GT = 0x28 , LT = 0x29 , LE = 0x2a ,
GE = 0x2b , NEQ = 0x2c , EQ = 0x2d , LEN = 0x2e ,
EMPTY = 0x2f , TAIL = 0x30 , HEAD = 0x31 , ISNIL = 0x32 ,
ASSERT = 0x33 , TO_NUM = 0x34 , TO_STR = 0x35 , AT = 0x36 ,
AT_AT = 0x37 , MOD = 0x38 , TYPE = 0x39 , HASFIELD = 0x3a ,
NOT = 0x3b , LOAD_CONST_LOAD_CONST = 0x3c , LOAD_CONST_STORE = 0x3d , LOAD_CONST_SET_VAL = 0x3e ,
STORE_FROM = 0x3f , STORE_FROM_INDEX = 0x40 , SET_VAL_FROM = 0x41 , SET_VAL_FROM_INDEX = 0x42 ,
INCREMENT = 0x43 , INCREMENT_BY_INDEX = 0x44 , INCREMENT_STORE = 0x45 , DECREMENT = 0x46 ,
DECREMENT_BY_INDEX = 0x47 , DECREMENT_STORE = 0x48 , STORE_TAIL = 0x49 , STORE_TAIL_BY_INDEX = 0x4a ,
STORE_HEAD = 0x4b , STORE_HEAD_BY_INDEX = 0x4c , STORE_LIST = 0x4d , SET_VAL_TAIL = 0x4e ,
SET_VAL_TAIL_BY_INDEX = 0x4f , SET_VAL_HEAD = 0x50 , SET_VAL_HEAD_BY_INDEX = 0x51 , CALL_BUILTIN = 0x52 ,
CALL_BUILTIN_WITHOUT_RETURN_ADDRESS = 0x53 , LT_CONST_JUMP_IF_FALSE = 0x54 , LT_CONST_JUMP_IF_TRUE = 0x55 , LT_SYM_JUMP_IF_FALSE = 0x56 ,
GT_CONST_JUMP_IF_TRUE = 0x57 , GT_CONST_JUMP_IF_FALSE = 0x58 , GT_SYM_JUMP_IF_FALSE = 0x59 , EQ_CONST_JUMP_IF_TRUE = 0x5a ,
EQ_SYM_INDEX_JUMP_IF_TRUE = 0x5b , NEQ_CONST_JUMP_IF_TRUE = 0x5c , NEQ_SYM_JUMP_IF_FALSE = 0x5d , CALL_SYMBOL = 0x5e ,
CALL_CURRENT_PAGE = 0x5f , GET_FIELD_FROM_SYMBOL = 0x60 , GET_FIELD_FROM_SYMBOL_INDEX = 0x61 , AT_SYM_SYM = 0x62 ,
AT_SYM_INDEX_SYM_INDEX = 0x63 , AT_SYM_INDEX_CONST = 0x64 , CHECK_TYPE_OF = 0x65 , CHECK_TYPE_OF_BY_INDEX = 0x66 ,
APPEND_IN_PLACE_SYM = 0x67 , APPEND_IN_PLACE_SYM_INDEX = 0x68 , STORE_LEN = 0x69 , LT_LEN_SYM_JUMP_IF_FALSE = 0x6a ,
InstructionsCount
}
The different bytecodes are stored here.
enum class ValTableElemType { Number , String , PageAddr }
Enumeration to keep track of the type of a Compiler Value.
enum class ErrorKind {
VM , Module , Scope , Type ,
Index , Arity , DivisionByZero
}
Functions
bool operator== (const Namespace &A, const Namespace &B)
bool operator< (const Namespace &, const Namespace &)
const Node & getTrueNode ()
const Node & getFalseNode ()
const Node & getNilNode ()
const Node & getListNode ()
std::string typeToString (const Node &node) noexcept
void serializeToVecLE (std::integral auto number, std::vector< uint8_t > &out)
void serializeToVecBE (std::integral auto number, std::vector< uint8_t > &out)
void serializeOn2BytesToVecLE (std::integral auto number, std::vector< uint8_t > &out)
void serializeOn2BytesToVecBE (std::integral auto number, std::vector< uint8_t > &out)
template<std::integral T>
T deserializeLE (std::vector< uint8_t >::const_iterator begin, std::vector< uint8_t >::const_iterator end)
template<std::integral T>
T deserializeBE (std::vector< uint8_t >::const_iterator begin, std::vector< uint8_t >::const_iterator end)
bool operator< (const Closure &A, const Closure &B)
bool operator== (const Dict &A, const Dict &B)
long countOpenEnclosures (const std::string &line, char open, char close)
Count the open enclosure and its counterpart: (), {}, [].
void trimWhitespace (std::string &line)
Remove whitespaces at the start and end of a string.
std::vector< std::string > getAllKeywords ()
Compute a list of all the language keywords and builtins.
std::vector< std::pair< std::string, replxx::Replxx::Color > > getColorPerKeyword ()
Compute a list of pairs (word -> color) to be used for coloration by the REPL.
replxx::Replxx::completions_t hookCompletion (const std::vector< std::string > &words, const std::string &context, int &length)
void hookColor (const std::vector< std::pair< std::string, replxx::Replxx::Color > > &words_colors, const std::string &context, replxx::Replxx::colors_t &colors)
replxx::Replxx::hints_t hookHint (const std::vector< std::string > &words, const std::string &context, int &length, replxx::Replxx::Color &color)
bool operator== (const Node &A, const Node &B)
bool operator< (const Node &A, const Node &B)
std::optional< std::filesystem::path > testExtensions (const std::filesystem::path &folder, const std::string &package_path)
bool operator== (const ScopeView &A, const ScopeView &B)
bool operator== (const Closure &A, const Closure &B)
bool operator== (const ClosureScope &A, const ClosureScope &B)
Variables
Ark::internal::IsSpace IsSpace
Ark::internal::IsInlineSpace IsInlineSpace
Ark::internal::IsDigit IsDigit
Ark::internal::IsHex IsHex
Ark::internal::IsAlpha IsAlpha
Ark::internal::IsAlnum IsAlnum
Ark::internal::IsSymbol IsSymbol
const IsChar IsMinus ('-')
constexpr std::array< std::string_view, 11 > nodeTypes
Node types as string, in the same order as the enum NodeType.
constexpr std::array< std::string_view, 9 > keywords
List of available keywords in ArkScript.
constexpr std::array InstructionNames
constexpr std::array< std::string_view, 7 > errorKinds
constexpr std::array colors
Typedef Documentation
PageAddr_t
using Ark::internal::PageAddr_t = uint16_t
Definition at line 26 of file Closure.hpp.
Enumeration Type Documentation
ErrorKind
enum class Ark::internal::ErrorKind strong
Enumerator
VM
Module
Scope
Type
Index
Arity
DivisionByZero
Definition at line 9 of file ErrorKind.hpp.
Instruction
enum Ark::internal::Instruction : uint8_t
The different bytecodes are stored here.
Adding an operator
It must be referenced as well under include/Ark/Compiler/Common.hpp, in the operators table. The order of the operators below FIRST_OPERATOR must be the same as the one in the operators table from the aforementioned file.
Enumerator
NOP
SYM_TABLE_START
VAL_TABLE_START
CODE_SEGMENT_START
NUMBER_TYPE
STRING_TYPE
FUNC_TYPE
FILENAMES_TABLE_START
INST_LOC_TABLE_START
LOAD_SYMBOL
LOAD_SYMBOL_BY_INDEX
LOAD_CONST
POP_JUMP_IF_TRUE
STORE
SET_VAL
POP_JUMP_IF_FALSE
JUMP
RET
HALT
PUSH_RETURN_ADDRESS
CALL
CAPTURE
RENAME_NEXT_CAPTURE
BUILTIN
DEL
MAKE_CLOSURE
GET_FIELD
PLUGIN
LIST
APPEND
CONCAT
APPEND_IN_PLACE
CONCAT_IN_PLACE
POP_LIST
POP_LIST_IN_PLACE
SET_AT_INDEX
SET_AT_2_INDEX
POP
SHORTCIRCUIT_AND
SHORTCIRCUIT_OR
CREATE_SCOPE
RESET_SCOPE_JUMP
POP_SCOPE
GET_CURRENT_PAGE_ADDR
FIRST_OPERATOR
ADD
SUB
MUL
DIV
GT
LT
LE
GE
NEQ
EQ
LEN
EMPTY
TAIL
HEAD
ISNIL
ASSERT
TO_NUM
TO_STR
AT
AT_AT
MOD
TYPE
HASFIELD
NOT
LOAD_CONST_LOAD_CONST
LOAD_CONST_STORE
LOAD_CONST_SET_VAL
STORE_FROM
STORE_FROM_INDEX
SET_VAL_FROM
SET_VAL_FROM_INDEX
INCREMENT
INCREMENT_BY_INDEX
INCREMENT_STORE
DECREMENT
DECREMENT_BY_INDEX
DECREMENT_STORE
STORE_TAIL
STORE_TAIL_BY_INDEX
STORE_HEAD
STORE_HEAD_BY_INDEX
STORE_LIST
SET_VAL_TAIL
SET_VAL_TAIL_BY_INDEX
SET_VAL_HEAD
SET_VAL_HEAD_BY_INDEX
CALL_BUILTIN
CALL_BUILTIN_WITHOUT_RETURN_ADDRESS
LT_CONST_JUMP_IF_FALSE
LT_CONST_JUMP_IF_TRUE
LT_SYM_JUMP_IF_FALSE
GT_CONST_JUMP_IF_TRUE
GT_CONST_JUMP_IF_FALSE
GT_SYM_JUMP_IF_FALSE
EQ_CONST_JUMP_IF_TRUE
EQ_SYM_INDEX_JUMP_IF_TRUE
NEQ_CONST_JUMP_IF_TRUE
NEQ_SYM_JUMP_IF_FALSE
CALL_SYMBOL
CALL_CURRENT_PAGE
GET_FIELD_FROM_SYMBOL
GET_FIELD_FROM_SYMBOL_INDEX
AT_SYM_SYM
AT_SYM_INDEX_SYM_INDEX
AT_SYM_INDEX_CONST
CHECK_TYPE_OF
CHECK_TYPE_OF_BY_INDEX
APPEND_IN_PLACE_SYM
APPEND_IN_PLACE_SYM_INDEX
STORE_LEN
LT_LEN_SYM_JUMP_IF_FALSE
InstructionsCount
Definition at line 26 of file Instructions.hpp.
Keyword
enum class Ark::internal::Keyword strong
The different keywords available.
Enumerator
Fun
Let
Mut
Set
If
While
Begin
Import
Del
Definition at line 74 of file Common.hpp.
NodeType
enum class Ark::internal::NodeType strong
The different node types available.
Enumerator
Symbol
Capture
Keyword
String
Number
List
Spread
Field
Macro
Namespace
Unused
Definition at line 43 of file Common.hpp.
ParserMode
enum class Ark::internal::ParserMode strong
Enumerator
Interpret
Escape sequences and () will be replaced by their UTF8 representation and nil, respectively.
Raw
Keep all text as is without modifying it (useful for the code formatter)
Definition at line 30 of file Parser.hpp.
ValTableElemType
enum class Ark::internal::ValTableElemType strong
Enumeration to keep track of the type of a Compiler Value.
Enumerator
Number
String
PageAddr
Definition at line 25 of file ValTableElem.hpp.
Function Documentation
countOpenEnclosures()
long Ark::internal::countOpenEnclosures (const std::string & line, char open, char close)
Count the open enclosure and its counterpart: (), {}, [].
Parameters
line data to operate on
open the open char: (, { or [
close the closing char:), } or ]
Returns
positive if there are more open enclosures than closed. 0 when both are equal, negative otherwise
Referenced by Ark::Repl::getCodeBlock().
deserializeBE()
template<std::integral T> T Ark::internal::deserializeBE (std::vector< uint8_t >::const_iterator begin, std::vector< uint8_t >::const_iterator end)
Definition at line 56 of file IntegerSerializer.hpp.
Referenced by Ark::BytecodeReader::instLocations().
deserializeLE()
template<std::integral T> T Ark::internal::deserializeLE (std::vector< uint8_t >::const_iterator begin, std::vector< uint8_t >::const_iterator end)
Definition at line 45 of file IntegerSerializer.hpp.
Referenced by Ark::BytecodeReader::values().
getAllKeywords()
std::vector< std::string > Ark::internal::getAllKeywords ()
Compute a list of all the language keywords and builtins.
Returns
std::vector<std::string>
getColorPerKeyword()
std::vector< std::pair< std::string, replxx::Replxx::Color > > Ark::internal::getColorPerKeyword ()
Compute a list of pairs (word -> color) to be used for coloration by the REPL.
Returns
std::vector<std::pair<std::string, replxx::Replxx::Color>>
getFalseNode()
const Node & Ark::internal::getFalseNode ()
Definition at line 360 of file Node.cpp.
References Symbol.
Referenced by Ark::internal::MacroProcessor::evaluate().
getListNode()
const Node & Ark::internal::getListNode ()
Definition at line 372 of file Node.cpp.
References Symbol.
Referenced by Ark::internal::FunctionExecutor::applyMacro(), Ark::internal::MacroProcessor::evaluate(), and Ark::internal::FunctionExecutor::unify().
getNilNode()
const Node & Ark::internal::getNilNode ()
Definition at line 366 of file Node.cpp.
References Symbol.
Referenced by Ark::internal::ConditionalExecutor::applyMacro(), and Ark::internal::MacroProcessor::evaluate().
getTrueNode()
const Node & Ark::internal::getTrueNode ()
Definition at line 354 of file Node.cpp.
References Symbol.
Referenced by Ark::internal::MacroProcessor::evaluate().
hookColor()
void Ark::internal::hookColor (const std::vector< std::pair< std::string, replxx::Replxx::Color > > & words_colors, const std::string & context, replxx::Replxx::colors_t & colors)
Referenced by Ark::Repl::cuiSetup().
hookCompletion()
replxx::Replxx::completions_t Ark::internal::hookCompletion (const std::vector< std::string > & words, const std::string & context, int & length)
Referenced by Ark::Repl::cuiSetup().
hookHint()
replxx::Replxx::hints_t Ark::internal::hookHint (const std::vector< std::string > & words, const std::string & context, int & length, replxx::Replxx::Color & color)
Referenced by Ark::Repl::cuiSetup().
operator<() [1/3]
bool Ark::internal::operator< (const Closure & A, const Closure & B) inline noexcept
Definition at line 88 of file Closure.hpp.
operator<() [2/3]
bool Ark::internal::operator< (const Namespace & , const Namespace &) inline
Definition at line 27 of file Namespace.hpp.
operator<() [3/3]
bool Ark::internal::operator< (const Node & A, const Node & B)
Definition at line 388 of file Node.cpp.
operator==() [1/6]
bool Ark::internal::operator== (const Closure & A, const Closure & B) noexcept
Definition at line 41 of file Closure.cpp.
operator==() [2/6]
bool Ark::internal::operator== (const ClosureScope & A, const ClosureScope & B) noexcept
Definition at line 38 of file ClosureScope.cpp.
operator==() [3/6]
bool Ark::internal::operator== (const Dict & A, const Dict & B) inline noexcept
Definition at line 93 of file Dict.hpp.
operator==() [4/6]
bool Ark::internal::operator== (const Namespace & A, const Namespace & B) inline
Definition at line 21 of file Namespace.hpp.
References Ark::internal::Namespace::is_glob, Ark::internal::Namespace::name, and Ark::internal::Namespace::with_prefix.
Referenced by Ark::internal::Dict::Dict().
operator==() [5/6]
bool Ark::internal::operator== (const Node & A, const Node & B)
Definition at line 378 of file Node.cpp.
operator==() [6/6]
bool Ark::internal::operator== (const ScopeView & A, const ScopeView & B) noexcept
Definition at line 116 of file ScopeView.cpp.
serializeOn2BytesToVecBE()
void Ark::internal::serializeOn2BytesToVecBE (std::integral auto number, std::vector< uint8_t > & out)
Definition at line 37 of file IntegerSerializer.hpp.
Referenced by Ark::internal::IRCompiler::compile(), Ark::internal::IRCompiler::pushFileHeader(), Ark::internal::IRCompiler::pushFilenameTable(), Ark::internal::IRCompiler::pushInstLocTable(), Ark::internal::IRCompiler::pushSymbolTable(), and Ark::internal::IRCompiler::pushValueTable().
serializeOn2BytesToVecLE()
void Ark::internal::serializeOn2BytesToVecLE (std::integral auto number, std::vector< uint8_t > & out)
Definition at line 30 of file IntegerSerializer.hpp.
serializeToVecBE()
void Ark::internal::serializeToVecBE (std::integral auto number, std::vector< uint8_t > & out)
Definition at line 18 of file IntegerSerializer.hpp.
Referenced by Ark::internal::IRCompiler::pushInstLocTable().
serializeToVecLE()
void Ark::internal::serializeToVecLE (std::integral auto number, std::vector< uint8_t > & out)
Definition at line 10 of file IntegerSerializer.hpp.
Referenced by Ark::internal::IRCompiler::pushValueTable().
testExtensions()
std::optional< std::filesystem::path > Ark::internal::testExtensions (const std::filesystem::path & folder, const std::string & package_path)
Definition at line 190 of file ImportSolver.cpp.
Referenced by Ark::internal::ImportSolver::findFile().
trimWhitespace()
void Ark::internal::trimWhitespace (std::string & line)
Remove whitespaces at the start and end of a string.
Parameters
line string modified in place
Referenced by Ark::Repl::getLine().
typeToString()
std::string Ark::internal::typeToString (const Node & node) inline noexcept
Parameters
node
Returns
std::string a string corresponding to the node type
Definition at line 264 of file Node.hpp.
References nodeTypes, and Symbol.
Referenced by Ark::internal::ASTLowerer::compileExpression(), Ark::internal::ASTLowerer::compileFunction(), Ark::internal::ASTLowerer::compileLetMutSet(), Ark::internal::MacroProcessor::evaluate(), and Ark::internal::MacroProcessor::registerFuncDef().
Variable Documentation
colors
std::array Ark::internal::colors constexpr
Initial value:
= {
        fmt::color::beige,
        fmt::color::chartreuse,
        fmt::color::coral,
        fmt::color::cornflower_blue,
        fmt::color::khaki,
        fmt::color::dark_olive_green,
        fmt::color::dark_orange,
        fmt::color::dark_salmon,
        fmt::color::fire_brick,
        fmt::color::forest_green,
        fmt::color::honey_dew,
        fmt::color::medium_orchid,
        fmt::color::medium_turquoise,
        fmt::color::peru,
        fmt::color::sea_green,
        fmt::color::tomato,
        fmt::color::wheat,
        fmt::color::sea_shell
    }
Definition at line 8 of file Logger.cpp.
Referenced by Ark::Repl::cuiSetup(), and Ark::internal::Logger::Logger().
errorKinds
std::array<std::string_view, 7> Ark::internal::errorKinds constexpr
Initial value:
= {
        "VMError",
        "ModuleError",
        "ScopeError",
        "TypeError",
        "IndexError",
        "ArityError",
        "DivisionByZero"
    }
Definition at line 20 of file ErrorKind.hpp.
Referenced by Ark::VM::throwVMError().
InstructionNames
std::array Ark::internal::InstructionNames constexpr
Definition at line 431 of file Instructions.hpp.
Referenced by Ark::BytecodeReader::display(), and Ark::internal::IRCompiler::dumpToStream().
IsAlnum
Ark::internal::IsAlnum Ark::internal::IsAlnum
IsAlpha
Ark::internal::IsAlpha Ark::internal::IsAlpha
IsDigit
Ark::internal::IsDigit Ark::internal::IsDigit
IsHex
Ark::internal::IsHex Ark::internal::IsHex
IsInlineSpace
Ark::internal::IsInlineSpace Ark::internal::IsInlineSpace
IsMinus
const IsChar Ark::internal::IsMinus('-') ('-')
Referenced by Ark::internal::BaseParser::signedNumber().
IsSpace
Ark::internal::IsSpace Ark::internal::IsSpace
IsSymbol
Ark::internal::IsSymbol Ark::internal::IsSymbol
keywords
std::array<std::string_view, 9> Ark::internal::keywords constexpr
Initial value:
= {
        "fun",
        "let",
        "mut",
        "set",
        "if",
        "while",
        "begin",
        "import",
        "del"
    }
List of available keywords in ArkScript.
Definition at line 88 of file Common.hpp.
Referenced by Formatter::format(), Formatter::formatVariable(), and Ark::internal::Node::repr().
nodeTypes
std::array<std::string_view, 11> Ark::internal::nodeTypes constexpr
Initial value:
= {
        "Symbol",
        "Capture",
        "Keyword",
        "String",
        "Number",
        "List",
        "Spread",
        "Field",
        "Macro",
        "Namespace",
        "Unused"
    }
Node types as string, in the same order as the enum NodeType.
Definition at line 59 of file Common.hpp.
Referenced by JsonCompiler::_compile(), Ark::internal::Parser::letMutSet(), and typeToString().