ArkScript: Ark::internal::BaseParser Class Reference
Ark::internal::BaseParser Class Reference
#include <BaseParser.hpp>
Public Member Functions
BaseParser ()=default
Protected Member Functions
void initParser (const std::string &filename, const std::string &code)
FilePosition getCursor () const
CodeErrorContext generateErrorContextAtCurrentPosition () const
void error (const std::string &error, FilePosition start_at, const std::optional< CodeErrorContext > &additional_context=std::nullopt) const
Create an error context and throw an error containing said context.
void errorWithNextToken (const std::string &message, const std::optional< CodeErrorContext > &additional_context=std::nullopt)
Fetch the next token (space and paren delimited) to generate an error.
void expectSuffixOrError (char suffix, const std::string &context, const std::optional< CodeErrorContext > &additional_context=std::nullopt)
Check for a closing char or generate an error.
long getCount ()
std::size_t getSize () const
bool isEOF () const
void backtrack (long n)
Backtrack to a given position (this is NOT an offset!)
bool accept (const CharPred &t, std::string *s=nullptr)
check if a Character Predicate was able to parse, call next() if matching
bool expect (const CharPred &t, std::string *s=nullptr)
heck if a Character Predicate was able to parse, call next() if matching ; throw a CodeError if it doesn't match
std::string peek () const
bool space (std::string *s=nullptr)
bool inlineSpace (std::string *s=nullptr)
bool comment (std::string *s=nullptr)
std::string spaceComment ()
std::string newlineOrComment ()
bool prefix (char c)
bool number (std::string *s=nullptr)
bool signedNumber (std::string *s=nullptr)
bool hexNumber (unsigned length, std::string *s=nullptr)
bool name (std::string *s=nullptr)
bool sequence (const std::string &s)
bool packageName (std::string *s=nullptr)
bool anyUntil (const CharPred &delim, std::string *s=nullptr)
Match any char that do not match the predicate.
bool oneOf (std::initializer_list< std::string > words, std::string *s=nullptr)
Fetch a token and try to match one of the given words.
Protected Attributes
std::string m_filename
Private Member Functions
void registerNewLine (std::string::iterator it, std::size_t row)
Register the position of a new line, with an iterator pointing to the new line and the row number.
void next ()
getting next character and changing the values of count/row/col/sym
Private Attributes
std::string m_str
std::vector< std::pair< std::string::iterator, std::size_t > > m_it_to_row
A crude map of
position to line number to speed up line number computing.
std::string::iterator m_it
std::string::iterator m_next_it
utf8_char_t m_sym
The current utf8 character we're on.
FilePosition m_filepos
The position of the cursor in the file.
Detailed Description
Definition at line 24 of file BaseParser.hpp.
Constructor & Destructor Documentation
BaseParser()
Ark::internal::BaseParser::BaseParser () default
Member Function Documentation
accept()
bool Ark::internal::BaseParser::accept (const CharPred & t, std::string * s = nullptr) protected
check if a Character Predicate was able to parse, call next() if matching
Parameters
t a char predicate to match
s optional string to append the matching chars to
Returns
true if matched
Definition at line 154 of file BaseParser.cpp.
References Ark::internal::utf8_char_t::c_str(), Ark::internal::utf8_char_t::codepoint(), isEOF(), m_sym, and next().
Referenced by anyUntil(), Ark::internal::Parser::block(), comment(), expectSuffixOrError(), Ark::internal::Parser::field(), Ark::internal::Parser::functionArgs(), Ark::internal::Parser::functionCall(), hexNumber(), Ark::internal::Parser::import_(), inlineSpace(), Ark::internal::Parser::list(), Ark::internal::Parser::macro(), Ark::internal::Parser::macroArgs(), name(), Ark::internal::Parser::nil(), number(), packageName(), prefix(), sequence(), signedNumber(), space(), and Ark::internal::Parser::string().
anyUntil()
bool Ark::internal::BaseParser::anyUntil (const CharPred & delim, std::string * s = nullptr) protected
Match any char that do not match the predicate.
Parameters
delim delimiter predicate
s optional string to append the matching chars to
Returns
true if matched
Definition at line 330 of file BaseParser.cpp.
References accept().
Referenced by errorWithNextToken().
backtrack()
void Ark::internal::BaseParser::backtrack (long n) protected
Backtrack to a given position (this is NOT an offset!)
Parameters
n position in the source file (byte number)
Definition at line 82 of file BaseParser.cpp.
References Ark::internal::utf8_char_t::at(), Ark::internal::FilePosition::col, m_filepos, m_it, m_it_to_row, m_next_it, m_str, m_sym, and Ark::internal::FilePosition::row.
Referenced by Ark::internal::Parser::atom(), Ark::internal::Parser::function(), Ark::internal::Parser::import_(), Ark::internal::Parser::letMutSet(), Ark::internal::Parser::macro(), Ark::internal::Parser::macroArgs(), Ark::internal::Parser::node(), Ark::internal::Parser::process(), and Ark::internal::Parser::string().
comment()
bool Ark::internal::BaseParser::comment (std::string * s = nullptr) protected
Definition at line 215 of file BaseParser.cpp.
References accept().
Referenced by Ark::internal::Parser::block(), Ark::internal::Parser::condition(), Ark::internal::Parser::del(), Ark::internal::Parser::function(), Ark::internal::Parser::functionArgs(), Ark::internal::Parser::functionCall(), Ark::internal::Parser::import_(), Ark::internal::Parser::letMutSet(), Ark::internal::Parser::list(), Ark::internal::Parser::loop(), Ark::internal::Parser::macro(), Ark::internal::Parser::macroArgs(), Ark::internal::Parser::macroCondition(), newlineOrComment(), Ark::internal::Parser::nil(), Ark::internal::Parser::process(), spaceComment(), and Ark::internal::Parser::wrapped().
error()
void Ark::internal::BaseParser::error (const std::string & error, FilePosition start_at, const std::optional< CodeErrorContext > & additional_context = std::nullopt) const protected
Create an error context and throw an error containing said context.
Parameters
error an error message
start_at position in the file where the parsing for the erroneous token started
additional_context optional context created when a node is being parsed
Definition at line 127 of file BaseParser.cpp.
References Ark::internal::FilePosition::col, error(), getCursor(), m_filename, and Ark::internal::FilePosition::row.
Referenced by error(), errorWithNextToken(), expect(), Ark::internal::Parser::functionArgs(), Ark::internal::Parser::import_(), initParser(), Ark::internal::Parser::letMutSet(), Ark::internal::Parser::number(), and Ark::internal::Parser::string().
errorWithNextToken()
void Ark::internal::BaseParser::errorWithNextToken (const std::string & message, const std::optional< CodeErrorContext > & additional_context = std::nullopt) protected
Fetch the next token (space and paren delimited) to generate an error.
Parameters
message an error message
additional_context optional context created when a node is being parsed
Definition at line 140 of file BaseParser.cpp.
References anyUntil(), error(), and getCursor().
Referenced by Ark::internal::Parser::condition(), Ark::internal::Parser::del(), expectSuffixOrError(), Ark::internal::Parser::field(), Ark::internal::Parser::function(), Ark::internal::Parser::import_(), Ark::internal::Parser::letMutSet(), Ark::internal::Parser::loop(), Ark::internal::Parser::macro(), Ark::internal::Parser::macroArgs(), Ark::internal::Parser::macroCondition(), Ark::internal::Parser::node(), Ark::internal::Parser::process(), and Ark::internal::Parser::spread().
expect()
bool Ark::internal::BaseParser::expect (const CharPred & t, std::string * s = nullptr) protected
heck if a Character Predicate was able to parse, call next() if matching ; throw a CodeError if it doesn't match
Parameters
t a char predicate to match
s optional string to append the matching chars to
Returns
true if matched
Definition at line 170 of file BaseParser.cpp.
References Ark::internal::utf8_char_t::c_str(), Ark::internal::utf8_char_t::codepoint(), error(), getCursor(), m_sym, Ark::internal::CharPred::name, and next().
Referenced by Ark::internal::Parser::functionArgs().
expectSuffixOrError()
void Ark::internal::BaseParser::expectSuffixOrError (char suffix, const std::string & context, const std::optional< CodeErrorContext > & additional_context = std::nullopt) protected
Check for a closing char or generate an error.
Parameters
suffix a suffix char, eg " or) @param context can be "string", "node" ; represents a structure
additional_context optional context created when a node is being parsed
Definition at line 148 of file BaseParser.cpp.
References accept(), and errorWithNextToken().
Referenced by Ark::internal::Parser::block(), Ark::internal::Parser::functionCall(), Ark::internal::Parser::import_(), Ark::internal::Parser::list(), Ark::internal::Parser::macro(), Ark::internal::Parser::string(), and Ark::internal::Parser::wrapped().
generateErrorContextAtCurrentPosition()
CodeErrorContext Ark::internal::BaseParser::generateErrorContextAtCurrentPosition () const nodiscard protected
Definition at line 117 of file BaseParser.cpp.
References getCursor(), and m_filename.
Referenced by Ark::internal::Parser::block(), Ark::internal::Parser::functionCall(), Ark::internal::Parser::import_(), Ark::internal::Parser::list(), Ark::internal::Parser::macro(), and Ark::internal::Parser::wrapped().
getCount()
long Ark::internal::BaseParser::getCount () inline protected
Returns
distance in characters from the beginning of the file to the cursor
Definition at line 88 of file BaseParser.hpp.
Referenced by Ark::internal::Parser::atom(), Ark::internal::Parser::function(), Ark::internal::Parser::import_(), Ark::internal::Parser::letMutSet(), Ark::internal::Parser::macro(), Ark::internal::Parser::macroArgs(), Ark::internal::Parser::node(), Ark::internal::Parser::process(), and Ark::internal::Parser::string().
getCursor()
FilePosition Ark::internal::BaseParser::getCursor () const nodiscard protected
Definition at line 112 of file BaseParser.cpp.
References m_filepos.
Referenced by Ark::internal::Parser::atom(), error(), errorWithNextToken(), expect(), Ark::internal::Parser::field(), Ark::internal::Parser::function(), Ark::internal::Parser::functionArgs(), Ark::internal::Parser::functionCall(), generateErrorContextAtCurrentPosition(), Ark::internal::Parser::import_(), Ark::internal::Parser::letMutSet(), Ark::internal::Parser::macro(), Ark::internal::Parser::node(), Ark::internal::Parser::positioned(), Ark::internal::Parser::positioned(), Ark::internal::Parser::string(), and Ark::internal::Parser::wrapped().
getSize()
std::size_t Ark::internal::BaseParser::getSize () const inline nodiscard protected
Returns
file size in bytes
Definition at line 94 of file BaseParser.hpp.
hexNumber()
bool Ark::internal::BaseParser::hexNumber (unsigned length, std::string * s = nullptr) protected
Definition at line 287 of file BaseParser.cpp.
References accept().
Referenced by Ark::internal::Parser::string().
initParser()
void Ark::internal::BaseParser::initParser (const std::string & filename, const std::string & code) protected
Definition at line 64 of file BaseParser.cpp.
References error(), m_filename, m_filepos, m_it, m_next_it, m_str, m_sym, and next().
Referenced by Ark::internal::Parser::process().
inlineSpace()
bool Ark::internal::BaseParser::inlineSpace (std::string * s = nullptr) protected
Definition at line 201 of file BaseParser.cpp.
References accept().
Referenced by spaceComment().
isEOF()
bool Ark::internal::BaseParser::isEOF () const inline nodiscard protected
Returns
true if the cursor is positioned at the end of the file
Definition at line 100 of file BaseParser.hpp.
Referenced by accept(), Ark::internal::Parser::block(), Ark::internal::Parser::functionArgs(), Ark::internal::Parser::functionCall(), Ark::internal::Parser::import_(), Ark::internal::Parser::list(), Ark::internal::Parser::macroArgs(), newlineOrComment(), next(), Ark::internal::Parser::process(), spaceComment(), and Ark::internal::Parser::string().
name()
bool Ark::internal::BaseParser::name (std::string * s = nullptr) protected
Definition at line 298 of file BaseParser.cpp.
References accept().
Referenced by Ark::internal::Parser::del(), Ark::internal::Parser::field(), Ark::internal::Parser::functionArgs(), Ark::internal::Parser::import_(), Ark::internal::Parser::letMutSet(), Ark::internal::Parser::macro(), Ark::internal::Parser::macroArgs(), oneOf(), Ark::internal::Parser::spread(), Ark::internal::Parser::symbol(), and Ark::internal::Parser::wrapped().
newlineOrComment()
std::string Ark::internal::BaseParser::newlineOrComment () nodiscard protected
Definition at line 238 of file BaseParser.cpp.
References comment(), isEOF(), and space().
Referenced by Ark::internal::Parser::block(), Ark::internal::Parser::condition(), Ark::internal::Parser::del(), Ark::internal::Parser::function(), Ark::internal::Parser::functionArgs(), Ark::internal::Parser::functionCall(), Ark::internal::Parser::import_(), Ark::internal::Parser::letMutSet(), Ark::internal::Parser::list(), Ark::internal::Parser::loop(), Ark::internal::Parser::macro(), Ark::internal::Parser::macroArgs(), Ark::internal::Parser::macroCondition(), Ark::internal::Parser::nil(), Ark::internal::Parser::process(), and Ark::internal::Parser::wrapped().
next()
void Ark::internal::BaseParser::next () private
getting next character and changing the values of count/row/col/sym
Definition at line 40 of file BaseParser.cpp.
References Ark::internal::utf8_char_t::at(), Ark::internal::FilePosition::col, isEOF(), Ark::internal::utf8_char_t::isPrintable(), m_filepos, m_it, m_next_it, m_str, m_sym, registerNewLine(), Ark::internal::FilePosition::row, and Ark::internal::utf8_char_t::size().
Referenced by accept(), expect(), and initParser().
number()
bool Ark::internal::BaseParser::number (std::string * s = nullptr) protected
Definition at line 256 of file BaseParser.cpp.
References accept().
Referenced by signedNumber().
oneOf()
bool Ark::internal::BaseParser::oneOf (std::initializer_list< std::string > words, std::string * s = nullptr) protected
Fetch a token and try to match one of the given words.
Parameters
words list of words to match against
s optional string to append the matching chars to
Returns
true if matched
Definition at line 341 of file BaseParser.cpp.
References name().
Referenced by Ark::internal::Parser::block(), Ark::internal::Parser::condition(), Ark::internal::Parser::del(), Ark::internal::Parser::function(), Ark::internal::Parser::import_(), Ark::internal::Parser::letMutSet(), Ark::internal::Parser::loop(), Ark::internal::Parser::macro(), and Ark::internal::Parser::macroCondition().
packageName()
bool Ark::internal::BaseParser::packageName (std::string * s = nullptr) protected
Definition at line 319 of file BaseParser.cpp.
References accept().
Referenced by Ark::internal::Parser::import_().
peek()
std::string Ark::internal::BaseParser::peek () const nodiscard protected
Definition at line 182 of file BaseParser.cpp.
References Ark::internal::utf8_char_t::c_str(), and m_sym.
Referenced by Ark::internal::Parser::process().
prefix()
bool Ark::internal::BaseParser::prefix (char c) protected
Definition at line 249 of file BaseParser.cpp.
References accept().
Referenced by Ark::internal::Parser::wrapped().
registerNewLine()
void Ark::internal::BaseParser::registerNewLine (std::string::iterator it, std::size_t row) private
Register the position of a new line, with an iterator pointing to the new line and the row number.
Parameters
it
row
Definition at line 11 of file BaseParser.cpp.
References m_it_to_row, and m_str.
Referenced by next().
sequence()
bool Ark::internal::BaseParser::sequence (const std::string & s) protected
Definition at line 312 of file BaseParser.cpp.
References accept().
Referenced by Ark::internal::Parser::macroArgs(), and Ark::internal::Parser::spread().
signedNumber()
bool Ark::internal::BaseParser::signedNumber (std::string * s = nullptr) protected
Definition at line 269 of file BaseParser.cpp.
References accept(), Ark::internal::IsMinus, and number().
Referenced by Ark::internal::Parser::number().
space()
bool Ark::internal::BaseParser::space (std::string * s = nullptr) protected
Definition at line 187 of file BaseParser.cpp.
References accept().
Referenced by Ark::internal::Parser::import_(), and newlineOrComment().
spaceComment()
std::string Ark::internal::BaseParser::spaceComment () nodiscard protected
Definition at line 227 of file BaseParser.cpp.
References comment(), inlineSpace(), and isEOF().
Referenced by Ark::internal::Parser::process(), and Ark::internal::Parser::wrapped().
Member Data Documentation
m_filename
std::string Ark::internal::BaseParser::m_filename protected
Definition at line 50 of file BaseParser.hpp.
Referenced by error(), generateErrorContextAtCurrentPosition(), initParser(), Ark::internal::Parser::positioned(), and Ark::internal::Parser::positioned().
m_filepos
FilePosition Ark::internal::BaseParser::m_filepos private
The position of the cursor in the file.
Definition at line 34 of file BaseParser.hpp.
Referenced by backtrack(), getCursor(), initParser(), and next().
m_it
std::string::iterator Ark::internal::BaseParser::m_it private
Definition at line 32 of file BaseParser.hpp.
Referenced by backtrack(), initParser(), and next().
m_it_to_row
std::vector<std::pair<std::string::iterator, std::size_t> > Ark::internal::BaseParser::m_it_to_row private
A crude map of
position to line number to speed up line number computing.
Definition at line 31 of file BaseParser.hpp.
Referenced by backtrack(), and registerNewLine().
m_next_it
std::string::iterator Ark::internal::BaseParser::m_next_it private
Definition at line 32 of file BaseParser.hpp.
Referenced by backtrack(), initParser(), and next().
m_str
std::string Ark::internal::BaseParser::m_str private
Definition at line 30 of file BaseParser.hpp.
Referenced by backtrack(), initParser(), next(), and registerNewLine().
m_sym
utf8_char_t Ark::internal::BaseParser::m_sym private
The current utf8 character we're on.
Definition at line 33 of file BaseParser.hpp.
Referenced by accept(), backtrack(), expect(), initParser(), next(), and peek().
The documentation for this class was generated from the following files:
/Users/fola/Documents/ArkScript/Ark/include/Ark/Compiler/AST/BaseParser.hpp
/Users/fola/Documents/ArkScript/Ark/src/arkreactor/Compiler/AST/BaseParser.cpp