ArkScript: Ark::internal::SharedLibrary Class Reference
Ark::internal::SharedLibrary Class Reference
Handling a shared library as an ArkScript VM plugin.
#include <SharedLibrary.hpp>
Public Member Functions
SharedLibrary ()
Construct a new Shared Library object.
SharedLibrary (const SharedLibrary &)=delete
Disable copy semantics as this contains a pointer.
SharedLibrary & operator= (const SharedLibrary &)=delete
Disable copy semantics as this contains a pointer.
SharedLibrary (std::string path)
Construct a new Shared Library object.
~SharedLibrary ()
Destroy the Shared Library object.
void load (const std::string &path)
Load a shared library.
void unload () const
Unload the shared library.
const std::string & path () const
template<typename T >
T get (const std::string &procname)
Return a function from the shared library.
Private Attributes
std::string m_path
bool m_loaded
Detailed Description
Handling a shared library as an ArkScript VM plugin.
Definition at line 35 of file SharedLibrary.hpp.
Constructor & Destructor Documentation
SharedLibrary() [1/3]
Ark::internal::SharedLibrary::SharedLibrary ()
Construct a new Shared Library object.
Definition at line 8 of file SharedLibrary.cpp.
SharedLibrary() [2/3]
Ark::internal::SharedLibrary::SharedLibrary (const SharedLibrary &) delete
Disable copy semantics as this contains a pointer.
SharedLibrary() [3/3]
Ark::internal::SharedLibrary::SharedLibrary (std::string path) explicit
Construct a new Shared Library object.
Parameters
path path to the shared library
Definition at line 13 of file SharedLibrary.cpp.
References load(), and m_path.
~SharedLibrary()
Ark::internal::SharedLibrary::~SharedLibrary ()
Destroy the Shared Library object.
Definition at line 21 of file SharedLibrary.cpp.
References unload().
Member Function Documentation
get()
template<typename T > T Ark::internal::SharedLibrary::get (const std::string & procname) inline
Return a function from the shared library.
Template Parameters
T the type of the function to retrieve
Parameters
procname the name of the function to retrieve
Returns
T the function from the shared library, if it was found
Definition at line 92 of file SharedLibrary.hpp.
load()
void Ark::internal::SharedLibrary::load (const std::string & path)
Load a shared library.
Parameters
path path to the shared library
Definition at line 26 of file SharedLibrary.cpp.
References m_loaded, m_path, path(), and unload().
Referenced by SharedLibrary().
operator=()
SharedLibrary & Ark::internal::SharedLibrary::operator= (const SharedLibrary &) delete
Disable copy semantics as this contains a pointer.
path()
const std::string & Ark::internal::SharedLibrary::path () const inline nodiscard
Definition at line 82 of file SharedLibrary.hpp.
Referenced by load().
unload()
void Ark::internal::SharedLibrary::unload () const
Unload the shared library.
Definition at line 49 of file SharedLibrary.cpp.
References m_loaded.
Referenced by load(), and ~SharedLibrary().
Member Data Documentation
m_loaded
bool Ark::internal::SharedLibrary::m_loaded private
Definition at line 119 of file SharedLibrary.hpp.
Referenced by load(), and unload().
m_path
std::string Ark::internal::SharedLibrary::m_path private
Definition at line 118 of file SharedLibrary.hpp.
Referenced by load(), and SharedLibrary().
The documentation for this class was generated from the following files:
/Users/fola/Documents/ArkScript/Ark/include/Ark/VM/SharedLibrary.hpp
/Users/fola/Documents/ArkScript/Ark/src/arkreactor/VM/SharedLibrary.cpp