ArkScript: Ark::internal::ImportSolver Class Reference
Ark::internal::ImportSolver Class Reference final
#include <ImportSolver.hpp>
Classes
struct ImportWithSource
Public Member Functions
ImportSolver (unsigned debug, const std::vector< std::filesystem::path > &libenv)
Create a new ImportSolver.
ImportSolver & setup (const std::filesystem::path &root, const std::vector< Import > &origin_imports)
Configure the ImportSolver.
void process (const Node &origin_ast) override
Start processing the given AST.
const Node & ast () const noexcept override
Output of the compiler pass.
Public Member Functions inherited from Ark::internal::Pass
Pass (std::string name, unsigned debug_level)
Construct a new Pass object.
virtual ~Pass ()=default
Private Member Functions
std::pair< Node, bool > findAndReplaceImports (const Node &ast)
Visits the AST, looking for import nodes to replace with their parsed module version.
std::vector< ImportWithSource > parseImport (const std::filesystem::path &source, const Import &import)
Parse a given file and returns a list of its imports. The AST is parsed and stored in m_modules[import.prefix].
std::filesystem::path findFile (const std::filesystem::path &file, const Import &import_) const
Search for an import file, using the root file path.
Private Attributes
unsigned m_debug_level
std::vector< std::filesystem::path > m_libenv
std::filesystem::path m_root
Folder were the entry file is.
Node m_ast
std::stack< ImportWithSource > m_imports
std::unordered_map< std::string, Package > m_packages
Package name to package AST & data mapping.
std::vector< std::string > m_imported
List of imports, in the order they were found and parsed.
Additional Inherited Members
Protected Attributes inherited from Ark::internal::Pass
Logger m_logger
Detailed Description
Definition at line 28 of file ImportSolver.hpp.
Constructor & Destructor Documentation
ImportSolver()
Ark::internal::ImportSolver::ImportSolver (unsigned debug, const std::vector< std::filesystem::path > & libenv)
Create a new ImportSolver.
Parameters
debug debug level
libenv list of paths to the standard library
Definition at line 13 of file ImportSolver.cpp.
Member Function Documentation
ast()
const Node & Ark::internal::ImportSolver::ast () const nodiscard override virtual noexcept
Output of the compiler pass.
Returns
const Node& the modified AST
Implements Ark::internal::Pass.
Definition at line 134 of file ImportSolver.cpp.
References m_ast.
Referenced by Ark::Welder::computeAST(), and findAndReplaceImports().
findAndReplaceImports()
std::pair< Node, bool > Ark::internal::ImportSolver::findAndReplaceImports (const Node & ast) private
Visits the AST, looking for import nodes to replace with their parsed module version.
Parameters
ast
Returns
Definition at line 67 of file ImportSolver.cpp.
References Ark::internal::Node::arkNamespace(), ast(), Ark::internal::Namespace::ast, Ark::internal::Begin, Ark::internal::Node::constList(), findAndReplaceImports(), Ark::internal::Import, Ark::internal::Keyword, Ark::internal::List, Ark::internal::Node::list(), m_imported, m_packages, Ark::internal::Node::nodeType(), and Ark::internal::Node::push_back().
Referenced by findAndReplaceImports(), and process().
findFile()
std::filesystem::path Ark::internal::ImportSolver::findFile (const std::filesystem::path & file, const Import & import_) const nodiscard private
Search for an import file, using the root file path.
Parameters
file path to the file containing the import
import_ current import directive
Returns
std::filesystem::path
Definition at line 200 of file ImportSolver.cpp.
References Ark::internal::FileSpan::end, m_libenv, m_root, Ark::internal::Import::packageToPath(), Ark::internal::testExtensions(), and Ark::internal::Import::toPackageString().
Referenced by parseImport().
parseImport()
std::vector< ImportSolver::ImportWithSource > Ark::internal::ImportSolver::parseImport (const std::filesystem::path & source, const Import & import) private
Parse a given file and returns a list of its imports. The AST is parsed and stored in m_modules[import.prefix].
Parameters
source path to the file containing the import
import current import directive
Returns
std::vector<ImportWithSource> imports found in the processed file
Definition at line 139 of file ImportSolver.cpp.
References Ark::internal::Parser::ast(), findFile(), Ark::internal::Import, Ark::internal::Parser::imports(), Ark::internal::List, m_debug_level, Ark::internal::Pass::m_logger, m_packages, Ark::internal::Parser::process(), Ark::Utils::readFile(), Ark::internal::Logger::traceEnd(), and Ark::internal::Logger::traceStart().
process()
void Ark::internal::ImportSolver::process (const Node & ast) override virtual
Start processing the given AST.
Parameters
ast
Implements Ark::internal::Pass.
Definition at line 28 of file ImportSolver.cpp.
References Ark::internal::Logger::debug(), findAndReplaceImports(), Ark::internal::ImportSolver::ImportWithSource::import, m_ast, m_imports, Ark::internal::Pass::m_logger, Ark::internal::Import::toPackageString(), Ark::internal::Logger::traceEnd(), and Ark::internal::Logger::traceStart().
Referenced by Ark::Welder::computeAST().
setup()
ImportSolver & Ark::internal::ImportSolver::setup (const std::filesystem::path & root, const std::vector< Import > & origin_imports)
Configure the ImportSolver.
Parameters
root path to the root file that imports all others
origin_imports the first imports to go through
Returns
ImportSolver& *this
Definition at line 17 of file ImportSolver.cpp.
References m_imports, and m_root.
Referenced by Ark::Welder::computeAST().
Member Data Documentation
m_ast
Node Ark::internal::ImportSolver::m_ast private
Definition at line 60 of file ImportSolver.hpp.
Referenced by ast(), and process().
m_debug_level
unsigned Ark::internal::ImportSolver::m_debug_level private
Definition at line 57 of file ImportSolver.hpp.
Referenced by parseImport().
m_imported
std::vector<std::string> Ark::internal::ImportSolver::m_imported private
List of imports, in the order they were found and parsed.
Definition at line 63 of file ImportSolver.hpp.
Referenced by findAndReplaceImports().
m_imports
std::stack<ImportWithSource> Ark::internal::ImportSolver::m_imports private
Definition at line 61 of file ImportSolver.hpp.
Referenced by process(), and setup().
m_libenv
std::vector<std::filesystem::path> Ark::internal::ImportSolver::m_libenv private
Definition at line 58 of file ImportSolver.hpp.
Referenced by findFile().
m_packages
std::unordered_map<std::string, Package> Ark::internal::ImportSolver::m_packages private
Package name to package AST & data mapping.
Definition at line 62 of file ImportSolver.hpp.
Referenced by findAndReplaceImports(), and parseImport().
m_root
std::filesystem::path Ark::internal::ImportSolver::m_root private
Folder were the entry file is.
Definition at line 59 of file ImportSolver.hpp.
Referenced by findFile(), and setup().
The documentation for this class was generated from the following files:
/Users/fola/Documents/ArkScript/Ark/include/Ark/Compiler/Package/ImportSolver.hpp
/Users/fola/Documents/ArkScript/Ark/src/arkreactor/Compiler/Package/ImportSolver.cpp