ArkScript: Ark::internal::MacroProcessor Class Reference
Ark::internal::MacroProcessor Class Reference final
The class handling the macros definitions and calls, given an AST.
#include <Processor.hpp>
Public Member Functions
MacroProcessor (unsigned debug) noexcept
Construct a new Macro Processor object.
void process (const Node &ast) override
Send the complete AST and work on it.
const Node & ast () const noexcept override
Return the modified AST.
Public Member Functions inherited from Ark::internal::Pass
Pass (std::string name, unsigned debug_level)
Construct a new Pass object.
virtual ~Pass ()=default
Private Member Functions
std::optional< Node > lookupDefinedFunction (const std::string &name) const
Return std::nullopt if the function isn't registered, otherwise return its node.
const Node * findNearestMacro (const std::string &name) const
Find the nearest macro matching a given name.
void deleteNearestMacro (const std::string &name)
Find the nearest macro matching a given name and delete it.
bool isConstEval (const Node &node) const
Check if a node can be evaluated at compile time.
void handleMacroNode (Node &node)
Registers macros based on their type, expand conditional macros.
void registerFuncDef (const Node &node)
Registers a function definition node.
void processNode (Node &node, unsigned depth, bool is_processing_namespace=false)
Register macros in scopes and apply them as needed.
bool applyMacro (Node &node, unsigned depth)
Apply a macro on a given node.
void checkMacroArgCountEq (const Node &node, std::size_t expected, const std::string &name, bool is_expansion=false, const std::string &kind="")
Check if the given node has exactly the provided argument count, otherwise throws an error.
void checkMacroArgCountGe (const Node &node, std::size_t expected, const std::string &name, const std::string &kind="")
Check if the given node has at least the provided argument count, otherwise throws an error.
Node evaluate (Node &node, unsigned depth, bool is_not_body=false)
Evaluate only the macros.
bool isTruthy (const Node &node)
Check if a node can be evaluated to true.
void throwMacroProcessingError (const std::string &message, const Node &node) const
Throw a macro processing error.
Static Private Member Functions
static bool isBeginNode (const Node &node)
Check if a given node is a list node, and starts with a Begin.
static void removeBegin (Node &node, std::size_t i)
Remove a begin block added by a macro.
Private Attributes
Node m_ast
The modified AST.
std::vector< MacroScope > m_macros
Handling macros in a scope fashion.
std::vector< Node > m_macros_being_applied
Stack of macros being applied. The last one is the current one we are working on.
std::shared_ptr< MacroExecutor > m_conditional_executor
std::vector< std::shared_ptr< MacroExecutor > > m_executors
std::unordered_map< std::string, Node > m_defined_functions
Friends
class MacroExecutor
Additional Inherited Members
Protected Attributes inherited from Ark::internal::Pass
Logger m_logger
Detailed Description
The class handling the macros definitions and calls, given an AST.
Definition at line 31 of file Processor.hpp.
Constructor & Destructor Documentation
MacroProcessor()
Ark::internal::MacroProcessor::MacroProcessor (unsigned debug) explicit noexcept
Construct a new Macro Processor object.
Parameters
debug the debug level
Definition at line 20 of file Processor.cpp.
Member Function Documentation
applyMacro()
bool Ark::internal::MacroProcessor::applyMacro (Node & node, unsigned depth) private
Apply a macro on a given node.
Parameters
node
depth
Returns
true if a macro was applied
false
Definition at line 187 of file Processor.cpp.
References m_executors, m_macros_being_applied, Ark::MaxMacroProcessingDepth, and throwMacroProcessingError().
Referenced by Ark::internal::MacroExecutor::applyMacroProxy(), evaluate(), handleMacroNode(), and processNode().
ast()
const Node & Ark::internal::MacroProcessor::ast () const nodiscard override virtual noexcept
Return the modified AST.
Returns
Node&
Implements Ark::internal::Pass.
Definition at line 45 of file Processor.cpp.
References m_ast.
Referenced by Ark::Welder::computeAST(), and process().
checkMacroArgCountEq()
void Ark::internal::MacroProcessor::checkMacroArgCountEq (const Node & node, std::size_t expected, const std::string & name, bool is_expansion = false, const std::string & kind = "") private
Check if the given node has exactly the provided argument count, otherwise throws an error.
Parameters
node a list node with a macro application, eg (= a b)
expected expected argument count, not counting the macro
name the name of the macro being applied
is_expansion if the error message should switch from "Interpreting ..." to "When expanding ..."
kind the macro kind, empty by default (eg "operator", "condition")
Definition at line 211 of file Processor.cpp.
References Ark::internal::Node::constList(), and throwMacroProcessingError().
Referenced by evaluate().
checkMacroArgCountGe()
void Ark::internal::MacroProcessor::checkMacroArgCountGe (const Node & node, std::size_t expected, const std::string & name, const std::string & kind = "") private
Check if the given node has at least the provided argument count, otherwise throws an error.
Parameters
node a list node with a macro application, eg (= a b)
expected expected argument count, not counting the macro
name the name of the macro being applied
kind the macro kind, empty by default (eg "operator", "condition")
Definition at line 238 of file Processor.cpp.
References Ark::internal::Node::constList(), and throwMacroProcessingError().
Referenced by evaluate().
deleteNearestMacro()
void Ark::internal::MacroProcessor::deleteNearestMacro (const std::string & name) private
Find the nearest macro matching a given name and delete it.
Parameters
name
Definition at line 675 of file Processor.cpp.
References m_macros.
Referenced by evaluate().
evaluate()
Node Ark::internal::MacroProcessor::evaluate (Node & node, unsigned depth, bool is_not_body = false) private
Evaluate only the macros.
Parameters
node
depth
is_not_body true if the method is run on a non-body code (eg a condition of an if-macro)
Returns
Node
Definition at line 253 of file Processor.cpp.
References Ark::internal::Language::And, applyMacro(), Ark::internal::Language::Argcount, Ark::internal::Language::AsIs, checkMacroArgCountEq(), checkMacroArgCountGe(), Ark::internal::Node::constList(), deleteNearestMacro(), evaluate(), findNearestMacro(), Ark::internal::Fun, Ark::internal::getFalseNode(), Ark::internal::getListNode(), Ark::internal::getNilNode(), Ark::internal::getTrueNode(), isConstEval(), isTruthy(), Ark::internal::Keyword, Ark::internal::List, Ark::internal::Node::list(), lookupDefinedFunction(), Ark::internal::Node::nodeType(), Ark::internal::Number, Ark::internal::Node::number(), Ark::internal::Language::Or, Ark::internal::Node::push_back(), Ark::internal::Language::Repr, Ark::internal::Node::repr(), Ark::internal::Node::setNodeType(), Ark::internal::Node::setPositionFrom(), Ark::internal::Node::setString(), Ark::internal::Spread, Ark::internal::String, Ark::internal::Node::string(), Ark::internal::Symbol, Ark::internal::Language::Symcat, throwMacroProcessingError(), std::to_string(), Ark::internal::Language::Type, Ark::internal::typeToString(), Ark::internal::Language::Undef, Ark::internal::Unused, and Ark::internal::Node::updateValueAndType().
Referenced by Ark::internal::MacroExecutor::evaluate(), evaluate(), and handleMacroNode().
findNearestMacro()
const Node * Ark::internal::MacroProcessor::findNearestMacro (const std::string & name) const nodiscard private
Find the nearest macro matching a given name.
Parameters
name
Returns
const Node* nullptr if no macro was found
Definition at line 662 of file Processor.cpp.
References m_macros.
Referenced by evaluate(), Ark::internal::MacroExecutor::findNearestMacro(), and isConstEval().
handleMacroNode()
void Ark::internal::MacroProcessor::handleMacroNode (Node & node) private
Registers macros based on their type, expand conditional macros.
Validate macros and register them by their name
Parameters
node A node of type Macro
Definition at line 50 of file Processor.cpp.
References applyMacro(), Ark::internal::Node::constList(), evaluate(), Ark::internal::List, Ark::internal::Node::list(), m_conditional_executor, m_macros, Ark::internal::Node::nodeType(), Ark::internal::Node::string(), and Ark::internal::Symbol.
Referenced by Ark::internal::MacroExecutor::handleMacroNode(), and processNode().
isBeginNode()
bool Ark::internal::MacroProcessor::isBeginNode (const Node & node) static private
Check if a given node is a list node, and starts with a Begin.
Parameters
node
Returns
true if it starts with a Begin
false
Definition at line 690 of file Processor.cpp.
References Ark::internal::Begin, Ark::internal::Node::constList(), Ark::internal::Keyword, Ark::internal::List, and Ark::internal::Node::nodeType().
Referenced by processNode().
isConstEval()
bool Ark::internal::MacroProcessor::isConstEval (const Node & node) const nodiscard private
Check if a node can be evaluated at compile time.
Parameters
node
Returns
true
false
Definition at line 719 of file Processor.cpp.
References Ark::internal::Builtins::builtins, Ark::internal::Capture, Ark::internal::Node::constList(), Ark::internal::Field, findNearestMacro(), Ark::internal::Keyword, Ark::internal::List, Ark::internal::Macro, Ark::internal::MutArg, Ark::internal::Namespace, Ark::internal::Node::nodeType(), Ark::internal::Number, Ark::internal::Language::operators, Ark::internal::RefArg, Ark::internal::Spread, Ark::internal::String, Ark::internal::Node::string(), Ark::internal::Symbol, and Ark::internal::Unused.
Referenced by evaluate().
isTruthy()
bool Ark::internal::MacroProcessor::isTruthy (const Node & node) private
Check if a node can be evaluated to true.
Parameters
node
Returns
true
false
Definition at line 639 of file Processor.cpp.
References Ark::internal::Node::nodeType(), Ark::internal::Number, Ark::internal::Node::number(), Ark::internal::Spread, Ark::internal::String, Ark::internal::Node::string(), Ark::internal::Symbol, and throwMacroProcessingError().
Referenced by evaluate(), and Ark::internal::MacroExecutor::isTruthy().
lookupDefinedFunction()
std::optional< Node > Ark::internal::MacroProcessor::lookupDefinedFunction (const std::string & name) const nodiscard private
Return std::nullopt if the function isn't registered, otherwise return its node.
Parameters
name function name
Returns
std::optional<Node>
Definition at line 655 of file Processor.cpp.
References m_defined_functions.
Referenced by evaluate().
process()
void Ark::internal::MacroProcessor::process (const Node & ast) override virtual
Send the complete AST and work on it.
Parameters
ast
Implements Ark::internal::Pass.
Definition at line 30 of file Processor.cpp.
References ast(), Ark::internal::Logger::debug(), Ark::internal::Node::debugPrint(), m_ast, Ark::internal::Pass::m_logger, processNode(), Ark::internal::Logger::shouldTrace(), Ark::internal::Logger::trace(), Ark::internal::Logger::traceEnd(), and Ark::internal::Logger::traceStart().
Referenced by Ark::Welder::computeAST().
processNode()
void Ark::internal::MacroProcessor::processNode (Node & node, unsigned depth, bool is_processing_namespace = false) private
Register macros in scopes and apply them as needed.
Parameters
node node on which to operate
depth
is_processing_namespace
Definition at line 102 of file Processor.cpp.
References applyMacro(), Ark::internal::Node::arkNamespace(), Ark::internal::Namespace::ast, Ark::internal::Node::constList(), handleMacroNode(), isBeginNode(), Ark::internal::List, Ark::internal::Node::list(), m_macros, Ark::internal::Macro, Ark::MaxMacroProcessingDepth, Ark::internal::Namespace, Ark::internal::Node::nodeType(), processNode(), registerFuncDef(), removeBegin(), throwMacroProcessingError(), and Ark::internal::Unused.
Referenced by process(), and processNode().
registerFuncDef()
void Ark::internal::MacroProcessor::registerFuncDef (const Node & node) private
Registers a function definition node.
Parameters
node
Definition at line 78 of file Processor.cpp.
References Ark::internal::Node::constList(), Ark::internal::Fun, Ark::internal::Keyword, Ark::internal::Let, Ark::internal::List, m_defined_functions, Ark::internal::Mut, Ark::internal::Node::nodeType(), Ark::internal::Set, Ark::internal::Node::string(), Ark::internal::Symbol, throwMacroProcessingError(), and Ark::internal::typeToString().
Referenced by processNode().
removeBegin()
void Ark::internal::MacroProcessor::removeBegin (Node & node, std::size_t i) static private
Remove a begin block added by a macro.
Parameters
node
i
Definition at line 698 of file Processor.cpp.
References Ark::internal::Begin, Ark::internal::Node::constList(), Ark::internal::Node::isListLike(), Ark::internal::Keyword, Ark::internal::Node::keyword(), Ark::internal::List, Ark::internal::Node::list(), and Ark::internal::Node::nodeType().
Referenced by processNode().
throwMacroProcessingError()
void Ark::internal::MacroProcessor::throwMacroProcessingError (const std::string & message, const Node & node) const private
Throw a macro processing error.
Parameters
message the error
node the node in which there is an error
Definition at line 762 of file Processor.cpp.
References Ark::internal::Node::filename(), m_macros_being_applied, and Ark::internal::Node::position().
Referenced by applyMacro(), checkMacroArgCountEq(), checkMacroArgCountGe(), evaluate(), isTruthy(), processNode(), registerFuncDef(), and Ark::internal::MacroExecutor::throwMacroProcessingError().
Friends And Related Symbol Documentation
MacroExecutor
friend class MacroExecutor friend
Definition at line 55 of file Processor.hpp.
Member Data Documentation
m_ast
Node Ark::internal::MacroProcessor::m_ast private
The modified AST.
Definition at line 58 of file Processor.hpp.
Referenced by ast(), and process().
m_conditional_executor
std::shared_ptr<MacroExecutor> Ark::internal::MacroProcessor::m_conditional_executor private
Definition at line 61 of file Processor.hpp.
Referenced by handleMacroNode().
m_defined_functions
std::unordered_map<std::string, Node> Ark::internal::MacroProcessor::m_defined_functions private
Definition at line 63 of file Processor.hpp.
Referenced by lookupDefinedFunction(), and registerFuncDef().
m_executors
std::vector<std::shared_ptr<MacroExecutor> > Ark::internal::MacroProcessor::m_executors private
Definition at line 62 of file Processor.hpp.
Referenced by applyMacro().
m_macros
std::vector<MacroScope> Ark::internal::MacroProcessor::m_macros private
Handling macros in a scope fashion.
Definition at line 59 of file Processor.hpp.
Referenced by deleteNearestMacro(), findNearestMacro(), handleMacroNode(), and processNode().
m_macros_being_applied
std::vector<Node> Ark::internal::MacroProcessor::m_macros_being_applied private
Stack of macros being applied. The last one is the current one we are working on.
Definition at line 60 of file Processor.hpp.
Referenced by applyMacro(), and throwMacroProcessingError().
The documentation for this class was generated from the following files:
/Users/fola/Documents/ArkScript/Ark/include/Ark/Compiler/Macros/Processor.hpp
/Users/fola/Documents/ArkScript/Ark/src/arkreactor/Compiler/Macros/Processor.cpp