ArkScript: Ark::internal::IRCompiler Class Reference
Ark::internal::IRCompiler Class Reference final
#include <IRCompiler.hpp>
Public Member Functions
IRCompiler (unsigned debug)
Create a new IRCompiler.
void process (const std::vector< IR::Block > &pages, const std::vector< std::string > &symbols, const std::vector< ValTableElem > &values)
Turn a given IR into bytecode.
void dumpToStream (std::ostream &stream) const
Dump the IR given to process to an output stream.
const bytecode_t & bytecode () const noexcept
Return the constructed bytecode object.
Private Member Functions
void compile ()
void pushWord (const Word &word)
Push a word (4 bytes) to the m_bytecode.
void pushFileHeader () noexcept
Push the file headers (magic, version used, timestamp)
void pushSymbolTable (const std::vector< std::string > &symbols)
void pushValueTable (const std::vector< ValTableElem > &values)
void pushFilenameTable ()
void pushInstLocTable (const std::vector< IR::Block > &pages)
Private Attributes
Logger m_logger
bytecode_t m_bytecode
std::vector< IR::Block > m_ir
std::vector< std::string > m_filenames
Detailed Description
Definition at line 25 of file IRCompiler.hpp.
Constructor & Destructor Documentation
IRCompiler()
Ark::internal::IRCompiler::IRCompiler (unsigned debug) explicit
Create a new IRCompiler.
Parameters
debug debug level
Definition at line 20 of file IRCompiler.cpp.
Member Function Documentation
bytecode()
const bytecode_t & Ark::internal::IRCompiler::bytecode () const nodiscard noexcept
Return the constructed bytecode object.
Returns
const bytecode_t&
Definition at line 105 of file IRCompiler.cpp.
References m_bytecode.
Referenced by Ark::Welder::generateBytecode().
compile()
void Ark::internal::IRCompiler::compile () private
Definition at line 110 of file IRCompiler.cpp.
References Ark::internal::CODE_SEGMENT_START, Ark::internal::IR::Goto, Ark::internal::IR::GotoWithArg, Ark::internal::HALT, Ark::internal::IR::Label, m_bytecode, m_ir, Ark::MaxValue16Bits, Ark::internal::IR::Opcode, Ark::internal::IR::Opcode2Args, pushWord(), and Ark::internal::serializeOn2BytesToVecBE().
Referenced by process().
dumpToStream()
void Ark::internal::IRCompiler::dumpToStream (std::ostream & stream) const
Dump the IR given to process to an output stream.
Parameters
stream output stream
Definition at line 68 of file IRCompiler.cpp.
References Ark::internal::IR::Goto, Ark::internal::IR::GotoWithArg, Ark::internal::InstructionNames, Ark::internal::IR::Label, m_ir, Ark::internal::IR::Opcode, and Ark::internal::IR::Opcode2Args.
Referenced by Ark::Welder::dumpIRToFile(), and Ark::Welder::textualIR().
process()
void Ark::internal::IRCompiler::process (const std::vector< IR::Block > & pages, const std::vector< std::string > & symbols, const std::vector< ValTableElem > & values)
Turn a given IR into bytecode.
Parameters
pages list of lists of IR entities generated by the compiler
symbols symbol table generated by the compiler
values value table generated by the compiler
Definition at line 24 of file IRCompiler.cpp.
References Ark::internal::CODE_SEGMENT_START, compile(), Ark::internal::HALT, Ark::internal::bytecode::HeaderSize, m_bytecode, m_filenames, m_ir, m_logger, pushFileHeader(), pushFilenameTable(), pushInstLocTable(), pushSymbolTable(), pushValueTable(), Ark::internal::Logger::traceEnd(), and Ark::internal::Logger::traceStart().
Referenced by Ark::Welder::generateBytecode().
pushFileHeader()
void Ark::internal::IRCompiler::pushFileHeader () private noexcept
Push the file headers (magic, version used, timestamp)
Definition at line 179 of file IRCompiler.cpp.
References ARK_VERSION_MAJOR, ARK_VERSION_MINOR, ARK_VERSION_PATCH, m_bytecode, and Ark::internal::serializeOn2BytesToVecBE().
Referenced by process().
pushFilenameTable()
void Ark::internal::IRCompiler::pushFilenameTable () private
Definition at line 275 of file IRCompiler.cpp.
References Ark::internal::FILENAMES_TABLE_START, m_bytecode, m_filenames, Ark::MaxValue16Bits, and Ark::internal::serializeOn2BytesToVecBE().
Referenced by process().
pushInstLocTable()
void Ark::internal::IRCompiler::pushInstLocTable (const std::vector< IR::Block > & pages) private
Definition at line 293 of file IRCompiler.cpp.
References Ark::internal::INST_LOC_TABLE_START, Ark::internal::IR::Label, m_bytecode, m_filenames, Ark::internal::serializeOn2BytesToVecBE(), and Ark::internal::serializeToVecBE().
Referenced by process().
pushSymbolTable()
void Ark::internal::IRCompiler::pushSymbolTable (const std::vector< std::string > & symbols) private
Definition at line 210 of file IRCompiler.cpp.
References m_bytecode, Ark::MaxValue16Bits, Ark::internal::serializeOn2BytesToVecBE(), and Ark::internal::SYM_TABLE_START.
Referenced by process().
pushValueTable()
void Ark::internal::IRCompiler::pushValueTable (const std::vector< ValTableElem > & values) private
Definition at line 229 of file IRCompiler.cpp.
References Ark::internal::FUNC_TYPE, m_bytecode, Ark::MaxValue16Bits, Ark::internal::Number, Ark::internal::NUMBER_TYPE, Ark::internal::PageAddr, Ark::internal::ieee754::serialize(), Ark::internal::serializeOn2BytesToVecBE(), Ark::internal::serializeToVecLE(), Ark::internal::String, Ark::internal::STRING_TYPE, and Ark::internal::VAL_TABLE_START.
Referenced by process().
pushWord()
void Ark::internal::IRCompiler::pushWord (const Word & word) private
Push a word (4 bytes) to the m_bytecode.
Parameters
word
Definition at line 171 of file IRCompiler.cpp.
References Ark::internal::Word::byte_1, Ark::internal::Word::byte_2, Ark::internal::Word::byte_3, m_bytecode, and Ark::internal::Word::opcode.
Referenced by compile().
Member Data Documentation
m_bytecode
bytecode_t Ark::internal::IRCompiler::m_bytecode private
Definition at line 60 of file IRCompiler.hpp.
Referenced by bytecode(), compile(), process(), pushFileHeader(), pushFilenameTable(), pushInstLocTable(), pushSymbolTable(), pushValueTable(), and pushWord().
m_filenames
std::vector<std::string> Ark::internal::IRCompiler::m_filenames private
Definition at line 62 of file IRCompiler.hpp.
Referenced by process(), pushFilenameTable(), and pushInstLocTable().
m_ir
std::vector<IR::Block> Ark::internal::IRCompiler::m_ir private
Definition at line 61 of file IRCompiler.hpp.
Referenced by compile(), dumpToStream(), and process().
m_logger
Logger Ark::internal::IRCompiler::m_logger private
Definition at line 59 of file IRCompiler.hpp.
Referenced by process().
The documentation for this class was generated from the following files:
/Users/fola/Documents/ArkScript/Ark/include/Ark/Compiler/IntermediateRepresentation/IRCompiler.hpp
/Users/fola/Documents/ArkScript/Ark/src/arkreactor/Compiler/IntermediateRepresentation/IRCompiler.cpp