ArkScript: Ark::internal::bytecode Namespace Reference
Ark::internal::bytecode Namespace Reference
Variables
constexpr std::array Magic = { 'a', 'r', 'k', '\0' }
constexpr std::array Version
constexpr std::size_t TimestampLength = 8
constexpr std::size_t HeaderSize = Magic.size() + Version.size() + TimestampLength
Variable Documentation
HeaderSize
std::size_t Ark::internal::bytecode::HeaderSize = Magic.size() + Version.size() + TimestampLength constexpr
Definition at line 39 of file Common.hpp.
Referenced by Ark::State::configure(), Ark::internal::IRCompiler::process(), Ark::BytecodeReader::sha256(), Ark::BytecodeReader::symbols(), and Ark::BytecodeReader::timestamp().
Magic
std::array Ark::internal::bytecode::Magic = { 'a', 'r', 'k', '\0' } constexpr
Definition at line 29 of file Common.hpp.
Referenced by Ark::BytecodeReader::checkMagic(), and Ark::BytecodeReader::version().
TimestampLength
std::size_t Ark::internal::bytecode::TimestampLength = 8 constexpr
Definition at line 38 of file Common.hpp.
Version
std::array Ark::internal::bytecode::Version constexpr
Initial value:
= {
            ARK_VERSION_MAJOR & 0xff00,
            ARK_VERSION_MAJOR & 0x00ff,
            ARK_VERSION_MINOR & 0xff00,
            ARK_VERSION_MINOR & 0x00ff,
            ARK_VERSION_PATCH & 0xff00,
            ARK_VERSION_PATCH & 0x00ff
        }
Definition at line 30 of file Common.hpp.
Referenced by Ark::BytecodeReader::version().