ArkScript: Ark::types::details Namespace Reference
Ark::types::details Namespace Reference
Typedefs
template<typename T , typename... Ts>
using AllSame = std::enable_if_t<std::conjunction_v<std::is_same<T, Ts>...>>
Functions
template<int I>
bool checkN (const std::vector< Value > &args)
template<int I, typename T , typename... Ts>
bool checkN (const std::vector< Value > &args, T type, Ts... xs)
Typedef Documentation
AllSame
template<typename T , typename... Ts> using Ark::types::details::AllSame = std::enable_if_t<std::conjunction_v<std::is_same<T, Ts>...>>
Definition at line 27 of file TypeChecker.hpp.
Function Documentation
checkN() [1/2]
template<int I> bool Ark::types::details::checkN (const std::vector< Value > & args) nodiscard
Definition at line 30 of file TypeChecker.hpp.
Referenced by Ark::types::check(), and checkN().
checkN() [2/2]
template<int I, typename T , typename... Ts> bool Ark::types::details::checkN (const std::vector< Value > & args, T type, Ts... xs) nodiscard
Definition at line 36 of file TypeChecker.hpp.
References Ark::Any, and checkN().